### ISSUE TITLE
Split implementations into foo.go, foo_linux.go

### ISSUE THREAD

**Issue by joestringer** [cilium/ebpf#10]
It can be useful to split Linux-specific code into separate files, so that large programs which are written against the library can be compiled and unit-tested on other platforms, with stub implementations for the linux-specific portions. Otherwise as soon as some file in the user project imports the BPF library, it will cause compilation failures for developers on other platforms.

We have a few developers on Cilium who develop natively on OSX which this affects from time to time. Example commit which shifts the code around to achieve this:

https://github.com/cilium/cilium/commit/1d28c269b6c54de1b442a044a9bc76accb0e9058#diff-c2be647780ac9b1d4632bfb1b99a7c0a

**Comment by lmb** [comment]
Yeah annoying, I used to hit that when I was still using macOS as well. Maybe we can get away with something less invasive though. It should be enough to pull all uses of `unix` into a separate file, which we can then stub out for macOS.
