### ISSUE TITLE
reference to missing symbol BIT

### ISSUE THREAD

**Issue by lrouter** [cilium/ebpf#101]
When loading my elf  object file with ebpf library, it outputs a message:
`ebpf.NewCollectionWithOptions: program cls_xrt_parse_ingress: instruction 343: reference to missing symbol BIT`
What does this mean ?

**Comment by lmb** [comment]
You have an instruction in your program that references a variable or constant named `BIT`, but the library can't find information about it in the symbol table. Do you have anything named like that in your program?

Can you provide me the output of `llvm-readelf-10 -S --symbols <your file>`?

**Comment by lrouter** [comment]
Yes, there is a symbol named BIT. This is the grep message:
```
 3032   Symbol {
 3033     Name: BIT (822)
 3034     Value: 0x0
 3035     Size: 0
 3036     Binding: Global (0x1)
 3037     Type: None (0x0)
 3038     Other: 0
 3039     Section: Undefined (0x0)
 3040   }
```


[symbols.tar.gz](https://github.com/cilium/ebpf/files/4710599/symbols.tar.gz)

**Comment by lmb** [comment]
Looks pretty strange. It's a global symbol without a type or size. You need to show me how BIT is defined and used in your source code.

**Comment by lrouter** [comment]
Finally, I find that the BIT symbol is from the kernel which could generates bitmask. During elf file loading, the symbol could not be found.

**Comment by lmb** [comment]
So is it a macro or something? I'm still not sure whether this is a bug in your code or the library.

**Comment by lrouter** [comment]
Yes. BIT is a macro like this:
`#define BIT(nr) (1UL << (nr))`
