### ISSUE TITLE
error: unknown func bpf_l4_csum_replace#11

### ISSUE THREAD

**Issue by lrouter** [cilium/ebpf#103]
When running test ebpf kernel code, the loader throws a error message as cilium ebpf debug format:
```
221: (85) call bpf_l4_csum_replace#11
unknown func bpf_l4_csum_replace#11
```

What does this mean ? How to solve it ?

**Comment by lmb** [comment]
The error is from the kernel. Most likely, your kernel is too old (< 4.1). See https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md
