### ISSUE TITLE
Cilium eBPF is having bad perfromances during tests

### ISSUE THREAD

**Issue by ahmedoun94** [cilium/ebpf#1032]
Hello, 

I am currently benchmarking several network solutions like Cilium. The results of my tests are the same for cilium and cilium eBPF. I know that the performance with cilium eBPF must be much higher than that.

I set up my cluster with rke2 and installed cilium via Helm:

```sh
 helm install cilium cilium/cilium \
    --namespace kube-system \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost=10.4.140.227 \
    --set k8sServicePort=6443
```
When i run cilium status in any of the Cilium pods and look for the line reporting the status for “Host Routing” (which should state “BPF”) i see "Legacy".

So, after looking at the logs, i found this:

`level=info msg="BPF host routing requires enable-bpf-masquerade. Falling back to legacy host routing (enable-host-legacy-routing=true)." subsys=daemon`

and i decided to add this line to the installation command : 

```sh
    --set bpf.masquerade=true 
```
Now when i look for the line reporting the status for “Host Routing” i finaly see "BPF" but the tests results are still very low for eBPF.

**Environment**

- RKE2 Kubernetes Cluster

- OS : 

```sh
Linux 5.19.0-35-generic x86_64
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by lmb** [comment]
Hi, this repository contains a low level library used by cilium. It sounds like you want to create an issue in [cilium/cilium](https://github.com/cilium/cilium/issues) instead.

Please include actual numbers when recreating and also what environment you are running in. Baremetal? Some cloud provider?
