### ISSUE TITLE
Add support for XDP frags in the elf_reader

### ISSUE THREAD

**Issue by ptzianos** [cilium/ebpf#1036]
Since v5.18 of the kernel, it is possible for XDP programs to process packets with MTUs larger than the size of a physical page. The feature was initially called XDP multi-buffer support and then it was renamed to XDP frags.
There are a bunch of commits related to the implementation, but one that is relevant to the codebase is this: https://github.com/torvalds/linux/commit/c2f2cdbeffda7b153c19e0f3d73149c41026c0db.
In this commit, a new flag is introduced. This flag is then added to a program section annotated with the "xdp.frags" string. Looking at the rest of the codebase, I can't see any other flags or any other changes relevant to this library, so supporting this should involve only a small amount of changes. The flag is used by the verifier to perform extra checks.

**Comment by ptzianos** [comment]
@lmb I think this can be closed now right?

**Comment by lmb** [comment]
Thanks :)
