### ISSUE TITLE
Warn about non-supported flags in map specs

### ISSUE THREAD

**Issue by aditighag** [cilium/ebpf#1072]
When an LRU map spec has the `BPF_F_NO_PREALLOC` flag, the library fails to load BPF programs with the error - `map create: operation not supported (without BTF k/v)`. This is misleading, as the main issue here is that the kernel doesn't support these flags for LRU type maps.

The library could give hints about such not supported configurations while loading map specs. 

It could be a candidate for good first issues, but I'll leave the judgement call to you. /cc @ti-mo

**Comment by kwakubiney** [comment]
Looks like something I'd like to pick up after I wrap [this](https://github.com/cilium/ebpf/pull/1071) up since it's a similar problem,

**Comment by kwakubiney** [comment]
Similar misleading error is seen when `noPreallocFlag` is used with maps of type `BPF_MAP_TYPE_BLOOM_FILTER` , `BPF_MAP_TYPE_ARRAY` , `BPF_MAP_TYPE_ARRAY_OF_MAPS` , `BPF_MAP_TYPE_PERCPU_ARRAY` and `BPF_MAP_TYPE_RINGBUF` as well
