### ISSUE TITLE
Actual verifier error is ommited

### ISSUE THREAD

**Issue by anjmao** [cilium/ebpf#1103]
**Describe the bug**
I'm getting verifier error:
```
loading objects: field TcpSendmsg: program tcp_sendmsg: load program: invalid argument: invalid func unknown#195896080 (10 line(s) omitted)
```

Due to this code here only last 1 or 2 lines are added to the error:

https://github.com/cilium/ebpf/blob/main/internal/errors.go#L72

**Expected behavior**
In local ebpf fork I changed it to print all lines and got more clear error:

```
func#0 @0 btf_vmlinux is malformed Unrecognized arg#0 type PTR 0: R1=ctx(id=0,off=0,imm=0) R10=fp0 ; int BPF_KPROBE(tcp_sendmsg, struct sock *sk, struct msghdr *msg, size_t size) 0: (bf) r6 = r1 1: R1=ctx(id=0,off=0,imm=0) R6_w=ctx(id=0,off=0,imm=0) R10=fp0 ; int BPF_KPROBE(tcp_sendmsg, struct sock *sk, struct msghdr *msg, size_t size) 1: (85) call unknown#195896080 invalid func unknown#195896080
```

In my case the issue was that I specified custom vmlinux btf file from amd64 for arm64 arch. First few lines actually helped me to find this issue as it mentions `btf_vmlinux is malformed Unrecognized arg#0 type PTR`

I think the easiest fix would be to expose VerifierError as public type in `errors` package. It contains original Log field which consumers could use. I would leave ErrorWithLog ctor inside internal/errors.go since it's not useful on public api.

**Comment by lmb** [comment]
Does this help? https://pkg.go.dev/github.com/cilium/ebpf#VerifierError

**Comment by anjmao** [comment]
Oh sorry, missed this one. Yes, this helps, thanks!
