### ISSUE TITLE
support compile once, run everywhere (CO-RE)

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#114]
libbpf supports modifying BPF bytecode to adjust for differences in kernel structure layouts. This is extremely useful for tracing programs that want to introspect kernel state, since you can now compile them against one kernel version but run them against another one.

Constituent parts:
- [x] Field based relocations (existence, size, offset)
- [x] Field signedness
- [x] Type based relocations
- [x] Enum based relocations
- [x] #384

**Comment by brycekahle** [comment]
👋  I'm going to give implementing simple CO-RE relocations a try. If anyone has any suggestions, I'd love to hear them!

**Comment by lmb** [comment]
Hi Bryce, great! Let me know if I can help you in any way. If you want we can use this issue to discuss issues / potential designs.

**Comment by lmb** [comment]
@brycekahle thanks for the inital set of PRs! Sorry for the delay in reviewing them, we had a long weekend here.

**Comment by brycekahle** [comment]
OK. I have relocations working in my branch, but I want to add some automated tests. Do you have any thoughts on how to approach testing? There are many examples in `libbpf`, but they all rely on global variables which are not currently supported in this library. Perhaps using a map instead for the same type of in/out data transfer?

**Comment by lmb** [comment]
With global variables you mean read-write ones? There is support for constants with CollectionSpec.RewriteConstants.

Using a map is probably the most straight forward way.

**Comment by ti-mo** [comment]
@lmb with bitfield relo's done, what's left here? What is meant by `Field signedness`?

**Comment by lmb** [comment]
Signedness was actually implemented by Jussi as part of the bitfield work, so this is complete! 🎉
