### ISSUE TITLE
link: link types are missing in gentypes

### ISSUE THREAD

**Issue by Asphaltt** [cilium/ebpf#1149]
By referencing `bpftool link`, there are two missing functions: `LinkGetNextID()` and `NewLinkFromID()`.

Then, when I want to implement them, `LinkGetNextIdAttr`, `LinkGetNextID()` and `LinkGetFDByID()` are missing in `sys/types.go` generated by `gentypes`.

I'm not familiar with `gentypes` to add the missing attr and funcs.

As a result, I'm not able to list all links. Or, I have to hack `link/link.go` to implement the missing functions by clumsy way.

**Comment by lmb** [comment]
True, I've been working on `gentypes` for #1117 and even I find it hard to modify. I'll see whether I can clean it up.

**Comment by lmb** [comment]
`link` now exposes an iterator. `gentypes` is still tricky, not sure when i'll get around to it though.
