### ISSUE TITLE
internal: stop parsing /proc/self/auxv once (Go 1.21)

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#1166]
From Go 1.21 is possible to extract the auxiliary vector from the runtime: https://cs.opensource.google/go/x/sys/+/refs/tags/v0.13.0:cpu/runtime_auxv_go121.go This will allow us to get rid of a bunch of custom code which parses `/proc/self/auxv` once 1.21 is the minimum version required by the lib.

We can just vendor the linked file and call `runtime_getAuxv`.

**Comment by kwakubiney** [comment]
Could take a stab at this

**Comment by paulcacheux** [comment]
I'm going to draft a PR for this if it's OK for you
