### ISSUE TITLE
example xdp: The IP address output by xdp demo is empty

### ISSUE THREAD

**Issue by BillyChen1** [cilium/ebpf#1175]
**Describe the bug**
The IP address output by [xdp demo](https://github.com/cilium/ebpf/tree/main/examples/xdp) is empty (NIL)

**To Reproduce**

Env:
```sh
~ go version
go version go1.21.1 linux/amd64
~ uname -a
Linux cqm-OptiPlex-7040 5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
~ cat /etc/issue
Ubuntu 20.04.5 LTS \n \l
```

Behavior:
```sh
xdp git:(main) ✗ sudo ./xdp enp0s31f6
2023/10/19 16:56:15 Attached XDP program to iface "enp0s31f6" (index 2)
2023/10/19 16:56:15 Press Ctrl-C to exit and remove the program
2023/10/19 16:56:16 Map contents:
        <nil> => 1
        <nil> => 1
        <nil> => 61
2023/10/19 16:56:17 Map contents:
        <nil> => 1
        <nil> => 5
        <nil> => 2
        <nil> => 1
        <nil> => 164
```

**Expected behavior**
My expectation was to see the IP address string.
I found that if I use the uint32 type in `examples/xdp/main.go` to accept the `val` attribute, and use `internal.NativeEndian.PutUint32` to convert it to a byte array, I can solve the problem.
The following is my modification to the `formatMapContents` method in[ `examples/xdp/main.go`](https://github.com/cilium/ebpf/blob/main/examples/xdp/main.go), which can solve this problem.
```golang
func formatMapContents(m *ebpf.Map) (string, error) {
	var (
		sb strings.Builder
		key uint32
		val uint32
	)
	iter := m.Iterate()
	for iter.Next(&key, &val) {
		b := make([]byte, 4)
		internal.NativeEndian.PutUint32(b, key)
		sourceIP := net.IP(b) // IPv4 source address in network byte order.
		packetCount := val
		sb.WriteString(fmt.Sprintf("\t%s => %d\n", sourceIP, packetCount))
	}
	return sb.String(), iter.Err()
}
```
After modification, the problem was solved.
```shell
➜  xdp git:(main) ✗ sudo ./xdp enp0s31f6
2023/10/19 17:08:20 Attached XDP program to iface "enp0s31f6" (index 2)
2023/10/19 17:08:20 Press Ctrl-C to exit and remove the program
2023/10/19 17:08:21 Map contents:
        114.212.81.84 => 16
        100.103.31.185 => 5
        172.27.144.197 => 1
2023/10/19 17:08:22 Map contents:
        114.212.81.84 => 43
        100.103.31.185 => 5
        120.55.98.112 => 2
        172.27.144.197 => 6
2023/10/19 17:08:23 Map contents:
        114.212.81.84 => 43
        100.103.31.185 => 7
        114.212.87.49 => 1
        120.55.98.112 => 2
        172.27.144.197 => 9
```

**Comment by rgo3** [comment]
I can confirm that this is also broken for me.
@markpash already [suggested](https://github.com/cilium/ebpf/pull/706#discussion_r897103949) on the PR for this example, that we could use `netip.Addr` as the type for the `key`, which fixed it for me:
```
func formatMapContents(m *ebpf.Map) (string, error) {
	var (
		sb strings.Builder
		key netip.Addr
		val uint32
	)
	iter := m.Iterate()
	for iter.Next(&key, &val) {
                sourceIP := key
		packetCount := val
		sb.WriteString(fmt.Sprintf("\t%s => %d\n", sourceIP, packetCount))
	}
	return sb.String(), iter.Err()
}
```

**Comment by BillyChen1** [comment]
> I can confirm that this is also broken for me. @markpash already [suggested](https://github.com/cilium/ebpf/pull/706#discussion_r897103949) on the PR for this example, that we could use `netip.Addr` as the type for the `key`, which fixed it for me:
> 
> ```
> func formatMapContents(m *ebpf.Map) (string, error) {
> 	var (
> 		sb strings.Builder
> 		key netip.Addr
> 		val uint32
> 	)
> 	iter := m.Iterate()
> 	for iter.Next(&key, &val) {
>                 sourceIP := key
> 		packetCount := val
> 		sb.WriteString(fmt.Sprintf("\t%s => %d\n", sourceIP, packetCount))
> 	}
> 	return sb.String(), iter.Err()
> }
> ```

cool! It worked for me, too!

**Comment by rgo3** [comment]
Feel free to open a PR with the fix @BillyChen1

**Comment by BillyChen1** [comment]
@rgo3 #1178

**Comment by rgo3** [comment]
@lmb had some suspicions and this broke with 4609dc73fa846184b379ae1ee771cc9e95e2ecbc. So my suggested fix fixes the issue described here but there might be some underlying bug with the zero allocation stuff?
