### ISSUE TITLE
internal: use runtime.Pinner instead of runtime.KeepAlive (Go 1.21)

### ISSUE THREAD

**Issue by florianl** [cilium/ebpf#1184]
From Go 1.21 it is possible to pin Go objects with [`runtime.Pinner`](https://pkg.go.dev/runtime#Pinner). Currently, [`runtime.KeepAlive`](https://pkg.go.dev/runtime#KeepAlive) is used, which keeps Go objects reachable but does not prevent Go from moving them.

1. Modify `internal/cmd/gentypes` to add a method `func (*T) pin(p *runtime.Pinner)` to each generated struct. This method calls `p.Pin` for each `sys.Pointer` in the struct.
2. In the generated syscall functions like `LinkUpdate`, etc. allocate a pinner, call `attr.pin(p)` and `defer p.Unpin()`

To be determined: how expensive is it to allocate a new pinner all the time? The best way to evaluate this is to dust off the map iteration / lookup benchmarks.

**Comment by lmb** [comment]
Interesting! From the doc:

> If the pinned object itself contains pointers to Go objects, these objects must be pinned separately if they are going to be accessed from C code.

Sounds to me like we'd have to generate a call for each sys.Pointer?

**Comment by lmb** [comment]
Using runtime.Pinner is not appropriate for syscall arguments: https://groups.google.com/g/golang-dev/c/_r_GkDSHDeY
