### ISSUE TITLE
After loading the ebpf program, the memory occupies 100MB and has not been released

### ISSUE THREAD

**Issue by xlango** [cilium/ebpf#1262]
**Describe the bug**
After loading the ebpf program, the memory occupies 100MB and has not been released

```golang
        var err error
	// Load collection
	m.collection, err = ebpf.NewCollectionWithOptions(m.collectionSpec, m.options.VerifierOptions)
	if err != nil {
		return errors.New(fmt.Sprintf("error:%v , couldn't load eBPF programs, cs:%v", err, m.collectionSpec))
	}
```

**Comment by lmb** [comment]
Have you tried https://pkg.go.dev/github.com/cilium/ebpf/btf#FlushKernelSpec ?

**Comment by xlango** [comment]
The cpu usage is also high when I load ebpf file again, is there a way to deal with it

**Comment by xlango** [comment]
[mmtracemain_prof.zip](https://github.com/cilium/ebpf/files/13827927/mmtracemain_prof.zip)
This is my tracking memory situation, after loading a few hundred MB of memory did not free

**Comment by xlango** [comment]
My ebpf program is 2MB

**Comment by florianl** [comment]
Thanks for providing the memory profile. I did have a quick look at it.
While functionality from cilium/ebpf accounts for most allocations, it is gojue/ebpfmanager that is keeping this information in internal structures around, like [`Manager`](https://github.com/gojue/ebpfmanager/blob/5fa7c062383dd2ba8951bbe356ffaa67e44ea4ba/manager.go#L241), and does not free them after loading the eBPF programs and maps.
So my suggestion is to close this issue and look with gojue/ebpfmanager for a way to not keep cilium/ebpf.Collection and cilium/ebpf.CollectionSpec after loading the programs and maps in their internal structures.

**Comment by lmb** [comment]
Thanks for taking a look Florian, closing the issue.
