### ISSUE TITLE
The initial load of BTF using CO-RE mode takes up 40MB of memory

### ISSUE THREAD

**Issue by xlango** [cilium/ebpf#1311]
### Describe the bug

```markdown
The initial load of BTF using CO-RE mode takes up 40MB of memory
```

### How to reproduce

```shell
use CO-RE BTF
```

### Version information

github.com/cilium/ebpf v0.12.3

**Comment by lmb** [comment]
Please provide adequate steps to reproduce, in the best case you can create a git repository with a readme in it somewhere. Also include how you measure "takes 40MB of memory". Via `top`? Something else?
