### ISSUE TITLE
Add test suite for netkit devices

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#1350]
https://github.com/cilium/ebpf/pull/1257 proposes to add support for attaching netkit programs, but we don't want to take on a dependency to vishvananda/netlink, even for testing. We've decided to drop the netkit tests for now, since the patchset is small and largely based on existing code, and kernel support isn't shipping in major distros for a while.

This issue is for 2 things:
- add netkit support to https://github.com/jsimonetti/rtnetlink
- add tests for the behaviour introduced in https://github.com/cilium/ebpf/pull/1257

**Comment by ti-mo** [comment]
> @ti-mo I can work on adding netkit support to `jsimonetti/rtnetlink`

Perfect! Any ETA?

**Comment by brlbil** [comment]
Not sure, I will try to push a PR upstream as soon as time allows.

**Comment by brlbil** [comment]
@ti-mo we will need to wait for a new version of `golang.org/x/sys` package which should be released soon, at least according to their release history. Netkit related symbols are there but not in a tagged version yet.

**Comment by lmb** [comment]
Hi @brlbil! Any news?

**Comment by brlbil** [comment]
Hi @lmb We need some significant changes upstream. I will open an issue to discuss what would be the best way to proceed upstream.

**Comment by brlbil** [comment]
@lmb @ti-mo I have created an issue upstream for discussion https://github.com/jsimonetti/rtnetlink/issues/216

**Comment by brlbil** [comment]
The PR to merge drivers including `netkit`, https://github.com/jsimonetti/rtnetlink/pull/221
