### ISSUE TITLE
Add support for cgroup unix socket address hooks

### ISSUE THREAD

**Issue by slayerjain** [cilium/ebpf#1370]
Support for unix socketse have been added and released with linux kernel v6.7 and it would be nice to have it in cillium too. 

ref: https://github.com/torvalds/linux/commit/8b3cba987e6d9464bb533d957de923f891b57bf8

**Comment by kwakubiney** [comment]
Hi @slayerjain, please do you have any examples of programs (using the cgroup Unix socket hook) where you encountered failures in loading or performing operations with cilium/ebpf? I've created a sample program based on the kernel's self-tests, and it appears to load correctly. (https://github.com/torvalds/linux/blob/712e14250dd2907346617eba275c46f53db8fae7/tools/testing/selftests/bpf/progs/connect_unix_prog.c#L14)

**Comment by ti-mo** [comment]
@kwakubiney Are you sure? A new cgroup hook generally means we need to add a new attach type. The `sys.BPF_CGROUP_UNIX_*` constants have already been synced into our internal `sys/` package, but there's no section prefix matcher in `elf_sections.go` for it yet. If loading succeeds, that may be a bug.

**Comment by kwakubiney** [comment]
IIRC, it loaded normally. I'll dust of the test I made and confirm @ti-mo

**Comment by kwakubiney** [comment]
@ti-mo There are corresponding section prefixes in `elf_sections.go` introduced by this commit : https://github.com/cilium/ebpf/commit/c6b584471f1bc42b7761f1f5950942965e8bd05d

**Comment by ti-mo** [comment]
@kwakubiney Sorry! Was looking at program types, not attach types.. Closing this, thanks for investigating.
