### ISSUE TITLE
Allow changing line info data in btf.Line

### ISSUE THREAD

**Issue by MarcusWichelmann** [cilium/ebpf#1413]
### Describe the bug

I'd like to change the `line` field in the `btf.Line` structure for a single instruction of a program, but cannot find a way to do that.

#### Background

I'm templating an eBPF program by replacing a placeholder function in its instructions with some custom instructions. Then I use `WithMetadata()` (see https://github.com/cilium/ebpf/pull/832) to copy over the metadata of the first placeholder instruction (that has the symbol) to the new one. 

This works fine, but I'd like to also change the BTF line info for the first instruction to contain some information about the inserted logic so it can be recognized in an instruction dump / verifier log.

I could use `.WithSource(asm.Comment("ABC"))` for that, but this causes a `missing bpf_line_info for 1 funcs starting from func#1` verifier error, because the line info seems to go missing then.

What I probably need to do is, to retrieve the existing `bpf.Line` structure using `.Source().(*btf.Line)` and change its fields, but these are unexported, so there doesn't seem to be a way to do that.

I'd like to discuss what would be the preferred solution here, before I make a pull request.

### How to reproduce

Load an eBPF program and call this on the first instruction of a function (the one with the symbol):

```
insns[i] = insns[i].WithMetadata(insn.Metadata).WithSource(asm.Comment("ABC"))
```

Then try to load the program and check the verifier error.

### Version information

github.com/cilium/ebpf v0.14.0

**Comment by lmb** [comment]
I'm using the same functionality in the library for https://github.com/cilium/ebpf/pull/1402/commits I think we could just export the fields in `Line` as you suggested. cc @dylandreimerink

**Comment by dylandreimerink** [comment]
Yes. I think that would be alright. There isn't any guarding of values needed, so just exposing fields should be safe. Are you thinking of just exposing `Line` or the rest of the fields as well (seem odd otherwise).

**Comment by MarcusWichelmann** [comment]
Wow, you're fast.

@dylandreimerink Yeah would probably make sense to export all of them then.

Should I make a PR?

**Comment by MarcusWichelmann** [comment]
What would be your preferred solution? Are there other ways how invalid values can get into that structure which would make a validation before marshalling necessary instead of just checking in the setters? Or where would you put that validation?

**Comment by MarcusWichelmann** [comment]
Also there seems to be some validation already:

https://github.com/cilium/ebpf/blob/main/btf/ext_info.go#L594

Isn't that sufficient?

**Comment by lmb** [comment]
Do you care about line, column and file at all? The only thing that the verifier currently renders is the line, all the other bits can stay zero. We could consider just exporting `Line.Line`. As an alternative, we could turn any `Source` that is a `Stringer` into a `Line`:

```
if stringer, ok := ins.Source().(fmt.Stringer); ok {
   // synthesise line info with line 0, col 0, etc.
}
```

**Comment by MarcusWichelmann** [comment]
> As an alternative, we could turn any Source that is a Stringer into a Line.

That would also work. All I want is adding a comment. The file/line/column information of the placeholder that was replaced isn't that interesting in my case, anyway, so it could just be zero.

**Comment by MarcusWichelmann** [comment]
@lmb So we'll go that route? I'll submit a PR for that tomorrow.

**Comment by lmb** [comment]
@MarcusWichelmann SGTM.
