### ISSUE TITLE
AttachXDP failed on Ubuntu 20.04, kernel version is 5.4

### ISSUE THREAD

**Issue by loveyacper** [cilium/ebpf#1474]
### Describe the bug

`features.HaveProgramType(ebpf.XDP)` return success, but `link.AttachXDP` failed.

### How to reproduce

Env:  Ubuntu 20.04, kernel version 5.4
Code:
```golang
if err := features.HaveProgramType(ebpf.XDP); err == nil {
  lk, linkErr := link.AttachXDP(link.XDPOptions{
			Program:   objs.TrafficStat,
			Interface: iface.Index,
		})
  log.Info("Attach XDP result: %v", linkErr)
} 
```
Result:
> Attach XDP result: bpf_link not supported (requires >= v5.7)

### Version information

github.com/cilium/ebpf v0.14.0

**Comment by florianl** [comment]
Hi @loveyacper 

The eBPF program type XDP was introduced earlier (with 4.8 iirc) than `bpf_link` (5.7).  As a consequence, `bpf_link` is expected to not be available on a 5.4 kernel.
You can still load XDP programs, but you have to use another method, like `ip link set ...`. This package `cilium/ebpf` focuses on everything around the eBPF syscall - therefore it does not cover the loading via `ip link set ...`.
