### ISSUE TITLE
When I am deleting pod, I found some warning messages.

### ISSUE THREAD

**Issue by lrouter** [cilium/ebpf#149]
When I am deleting pod, I found some warning messages like this: `level=warning msg="Unable to update ipcache map entry on pod add" error="empty PodIPs"`.  But there is no error, so why does this message should be logged, and could it be deleted from source code ?

**Comment by lmb** [comment]
I think this issue belongs in https://github.com/cilium/cilium Please re-create it there, and provide some more info on your set up.

**Comment by lrouter** [comment]
ok. Thanks.
