### ISSUE TITLE
map Lookup allocates when key does not exist

### ISSUE THREAD

**Issue by brycekahle** [cilium/ebpf#1516]
### Describe the bug

In a hot loop of Lookup where a lot of keys do not exist, the `fmt.Errorf` at https://github.com/cilium/ebpf/blob/fbb9ed862764a07745604fc608dc09534e76cd36/map.go#L698 can allocate a decent chunk of memory

### How to reproduce

1. Create map
2. Do a bunch of lookups for keys that do not exist
3. Profile allocations

### Version information

github.com/cilium/ebpf v0.15.1-0.20240709101333-5976561b28aa

**Comment by lmb** [comment]
Can you add `top` output from pprof or similar? I wonder whether most of the cost is in `wrapMapError` or in `fmt.Errorf`. We could consider special casing ENOENT. Plus add a test so we don't regress (this sounds familiar!)

**Comment by brycekahle** [comment]
```
(pprof) top
Showing nodes accounting for 26991765, 74.69% of 36140090 total
Dropped 227 nodes (cum <= 180700)
Showing top 10 nodes out of 93
      flat  flat%   sum%        cum   cum%
   7618793 21.08% 21.08%    7618793 21.08%  fmt.Errorf
```

I don't see `wrapMapError` in my profiles at all.

**Comment by brycekahle** [comment]
![Screenshot 2024-07-18 at 10 57 21 AM](https://github.com/user-attachments/assets/10c397ec-ba53-4ee0-bdb7-3d80ddb6390c)
