### ISSUE TITLE
Issues with distributing eBPF programs to other machines

### ISSUE THREAD

**Issue by peterleezzzZflps** [cilium/ebpf#1556]
My eBPF program is in ubuntu 22.04, kernel version = 5.15.0-118-generic. This successfully builds the kernel-mode C program and the user-mode Golang program.

``` 
# cat /boot/config-5.15.0-118-generic  |grep BTF

CONFIG_VIDEO_SONY_BTF_MPX=m

CONFIG_DEBUG_INFO_BTF=y

CONFIG_PAHOLE_HAS_SPLIT_BTF=y

CONFIG_DEBUG_INFO_BTF_MODULES=y
```

This is a program that XDP parses http request payload
Makefile： 

```
CLANG ?= clang

CFLAGS ?= -O2 -g -Wall -Werror 

EBPF_ROOT = /root/application/golang/proj/src/eBPF-Observability/pkg/cbpf
MY_HEADERS = $(EBPF_ROOT)/headers

all: generate

generate: export BPF_CLANG = $(CLANG)
generate: export BPF_CFLAGS = $(CFLAGS)
generate: export BPF_HEADERS = $(MY_HEADERS)
generate:
	go generate ./...
```

go doc.go
```
package xdp

//go:generate bpf2go -cc $BPF_CLANG -cflags $BPF_CFLAGS docker_bpf docker.bpf.c -- -I $BPF_HEADERS
```

This is part of the code for loading kernel-mode programs in user mode: 
```
func LoaderXdp() {
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Panicln(err)
	}

	xdpBpfObjects := docker_bpfObjects{}
	err := loadDocker_bpfObjects(&xdpBpfObjects, nil)
	//err = loadDocker_bpfObjects(&xdpBpfObjects, opts)
	if err != nil {
		log.Panicln(err)
	}

	defer xdpBpfObjects.Close()

.......
}
```

My problem is that I built the eBPF program on a machine with BTF enabled and ran it without any problems, but I can't run it on a machine without BTF enabled 
`field XdpVeth: program xdp_veth: apply CO-RE relocations: load kernel spec: no BTF found for kernel version 5.19.0-1.el7.elrepo.x86_64: not supported`

***I want to know if the eBPF program I compiled on a machine with BTF enabled can be run on a machine without BTF enabled? Do I need to import an external .btf program myself? Just like btf.LoadSpec("xxx.btf") . I have searched many articles about CO-RE, but I have not found the answer I want. I hope to get a reply.***

In my plan, recompiling the kernel to enable BTF is the worst option, so I want to know whether this problem can be solved at runtime or at compile time.

**Comment by peterleezzzZflps** [comment]
> 您编译程序的机器是否支持 BTF 并不重要，这取决于编译器和提供的标志。此外，只要您不使用任何需要 BTF 的功能，就可以在没有 BTF 的内核上加载使用 BTF 支持编译的程序。但是，错误`apply CO-RE relocations`似乎表明您的程序使用了 CO-RE 重定位，或者至少您的编译器发出了它们。CO-RE 在编译期间以及在内核上都需要 BTF 才能工作。
> 
> [该库允许您通过ProgramOptions.KernelTypes](https://github.com/cilium/ebpf/blob/main/prog.go#L81)手动证明您的内核的 BTF 信息，该信息可以在调用[NewProgramWithOptions](https://github.com/cilium/ebpf/blob/main/prog.go#L217)或[NewCollectionWithOptions](https://github.com/cilium/ebpf/blob/main/collection.go#L367)时提供。
> 
> 该选项采用可以从[btf.LoadSpec](https://github.com/cilium/ebpf/blob/main/btf/btf.go#L183)或其他加载函数之一`*btf.Spec`获取的参数。这些参数解析包含 BTF 有线格式的文件或包含 BTF 的 ELF 文件。[](https://github.com/cilium/ebpf/blob/main/btf/btf.go#L183)
> 
> 您应该能够在https://github.com/aquasecurity/btfhub-archive/上找到适用于您内核的 BTF 文件，或者您也可以从您的内核自行生成一个 BTF文件https://github.com/aquasecurity/btfhub

Yes, thank you for your reply. I ignored the error about CO:RE before, but later I found that the cilium/ebpf loader automatically enabled the loading of CO:RE, and this option cannot be turned off. I can only load vmlinux instead through the kerneltypes parameter. Later, I provided the vmlinux file and it can run on a machine without BTF enabled.

**Comment by peterleezzzZflps** [comment]
> @peterleezzzZflps[对于ebpf 加载器项目](https://github.com/cilium/ebpf)来说，这可能是一个更好的问题。我已将此问题转移到那里。

thanks.

**Comment by ti-mo** [comment]
> I found that the cilium/ebpf loader automatically enabled the loading of CO:RE, and this option cannot be turned off.

CO-RE can't really be disabled. If your BPF C program depends on features that need CO-RE to work, the library will try to find and load a BTF blob to do the necessary plumbing. Otherwise, your program simply won't pass the verifier in most cases. Glad you got it to work!
