### ISSUE TITLE
request: support JumpOp by offset number

### ISSUE THREAD

**Issue by AkihiroSuda** [cilium/ebpf#16]
https://godoc.org/github.com/cilium/ebpf/asm#JumpOp.Imm

Jumping by offset number is still useful in some cases

**Comment by AkihiroSuda** [comment]
Assigning labels is tricky when the code generation logic is complicated, but I can close this issue as this is not a huge deal: https://github.com/AkihiroSuda/runc/blob/ed9df13f451950d3801eac17458b53dd94c10d0c/libcontainer/cgroups/ebpf/devicefilter/devicefilter.go#L117-L152

**Comment by lmb** [comment]
Sounds good. Please be aware that we'll probably have to change the API of the `asm` package to get BTF support, which will break your code. I'll ping you if that happens.

**Comment by AkihiroSuda** [comment]
thanks!
