### ISSUE TITLE
MapOptions PinPath doesn't work

### ISSUE THREAD

**Issue by CeerDecy** [cilium/ebpf#1637]
I have set `PinPath` in `ebpf.MapOptions`, but it doesn't work. 
I need to call Map's `Pin` function manually to get it to work.

```go
// https://eunomia.dev/zh/tutorials/29-sockops/#ebpf_1

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go bpf_redirect bpf_redirect.bpf.c -- -I../headers
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go bpf_contrack bpf_contrack.bpf.c -- -I../headers

func main() {

	mountPath := "/sys/fs/bpf/"

	if err := unix.Mount("bpf", mountPath, "bpf", 0, ""); err != nil {
		logrus.Fatalln(err)
	}

	var contrackObject bpf_contrackObjects
	if err := loadBpf_contrackObjects(&contrackObject, &ebpf.CollectionOptions{
		Maps: ebpf.MapOptions{
			PinPath:        mountPath,
			LoadPinOptions: ebpf.LoadPinOptions{},
		},
	}); err != nil {
		logrus.Infoln(err)
		return
	}
	defer contrackObject.Close()

	logrus.Infoln("MapOptions has pinned ====> ", contrackObject.SockOpsMap.IsPinned())

	if err := contrackObject.SockOpsMap.Pin(mountPath + "sock_ops_map"); err != nil {
		logrus.Fatalf("failed to pin map, error: %v", err)
	}

	logrus.Infoln("Custom has pinned ====> ", contrackObject.SockOpsMap.IsPinned())
}
```

running log
![Image](https://github.com/user-attachments/assets/66ae4c52-ab8e-4aa3-b11c-ff6a67ca09d4)

**Comment by kwakubiney** [comment]
Thanks for filing this but i am not sure there is an issue here. There is no API guarantee that loading the collection spec with a pin path would pin the map at the specified path without specifically calling `Pin` or `PinByName`.

**Comment by CeerDecy** [comment]
@kwakubiney Okay, I got it. Thanks for the answer.

**Comment by ti-mo** [comment]
@CeerDecy Setting PinPath alone is not sufficient, you also need to set the 'pinning' field in the map definition you want to pin in the ELF. (see https://github.com/cilium/ebpf/blob/e439d37e580e2d66e98f2b987f8ba0c295231439/testdata/loader.c#L28, use the actual LIBBPF_PIN_BY_NAME constant in your code)

**Comment by CeerDecy** [comment]
@ti-mo Oh, Thinks!!  I will try it
