### ISSUE TITLE
clang-8 binaries without debug info can't be loaded

### ISSUE THREAD

**Issue by arthurfabre** [cilium/ebpf#167]
When compiling BPF programs with clang-8 without debug info, `LoadCollectionSpec` fails with:

```
load programs: program no_relocation: no extended BTF info for section socket
```

To reproduce:

```
clang-8 -target bpf -O2 -Wall -Werror -c testdata/loader.c -o testdata/loader-clang-8-nodebug.elf
sudo -E (which go) test -v -run "TestLoadCollectionSpec" ./...
```

**Comment by arthurfabre** [comment]
I won't have time to look at this this week, but I can take a look next week if you want @lmb :)

**Comment by lmb** [comment]
Yes please!

**Comment by lmb** [comment]
Are you still planning on looking at this?

**Comment by arthurfabre** [comment]
I'm probably not going to have time to look at this anytime soon sorry :(
I couldn't reproduce this with `clang-9`, so maybe we should just close it and forget about it.
