### ISSUE TITLE
ptr_32_le and ptr_32_be are identical

### ISSUE THREAD

**Issue by AkihiroSuda** [cilium/ebpf#17]
https://github.com/cilium/ebpf/blob/60d34524c5b34180514b1aae150a53bc41026d81/ptr_32_le.go
https://github.com/cilium/ebpf/blob/60d34524c5b34180514b1aae150a53bc41026d81/ptr_32_be.go

I don't have big-endian machine, but maybe _be.go is wrong?

**Comment by lmb** [comment]
Good point. I admit that I've never tested 32bit little / big endian, as you can tell :) Mostly for lack of hardware.

Next step is to do some digging and check whether it has always been this way or not.
