### ISSUE TITLE
request: make bpfProgLoad and bpfCall public

### ISSUE THREAD

**Issue by AkihiroSuda** [cilium/ebpf#20]
[My PR for runc](https://github.com/opencontainers/runc/pull/2145/files#diff-1ef8c95433024da9b51fe88b2f63d559R44) depends on local copy of [`bpfProgLoad()`](https://github.com/cilium/ebpf/blob/60d34524c5b34180514b1aae150a53bc41026d81/syscalls.go#L191) and [`bpfCall()`](https://github.com/cilium/ebpf/blob/60d34524c5b34180514b1aae150a53bc41026d81/syscalls.go#L390).

Any chance to make these functions public?

**Comment by lmb** [comment]
I'd rather not make these functions public, since using them correctly depends on syscallPtr. In general it increases the API surface we need to support. What do we need to add for you to use NewProgram instead? Is the problem the missing BPF_PROG_TYPE_CGROUP_DEVICE or missing `Attach`?

**Comment by AkihiroSuda** [comment]
>  Is the problem the missing BPF_PROG_TYPE_CGROUP_DEVICE or missing Attach?

Both.

What I need is the following function:
```go
// LoadAttachCgroupDeviceFilter installs eBPF device filter program to /sys/fs/cgroup/<foo> directory.
//
// Requires the system to be running in cgroup2 unified-mode with kernel >= 4.15 .
//
// https://github.com/torvalds/linux/commit/ebc614f687369f9df99828572b1d85a7c2de3d92
func LoadAttachCgroupDeviceFilter(insts asm.Instructions, license string, dirFD uint32) error {
	buf := bytes.NewBuffer(make([]byte, 0, len(insts)*asm.InstructionSize))
	err := insts.Marshal(buf, cilium.NativeEndian)
	if err != nil {
		return err
	}

	bytecode := buf.Bytes()
	insCount := uint32(len(bytecode) / asm.InstructionSize)
	lic := []byte(license)
	loadAttr := &cilium.BPFProgLoadAttr{
		ProgType:     unix.BPF_PROG_TYPE_CGROUP_DEVICE,
		InsCount:     insCount,
		Instructions: cilium.NewPtr(unsafe.Pointer(&bytecode[0])),
		License:      cilium.NewPtr(unsafe.Pointer(&lic[0])),
	}
	bpfFD, err := cilium.BPFProgLoad(loadAttr)
	if err != nil {
		// TODO: obtain log on failure
		return errors.Wrap(err, "failed to call BPF_PROG_LOAD")
	}
	fd, err := bpfFD.Value()
	if err != nil {
		return errors.Wrap(err, "failed to get BPF fd")
	}
	attachAttr := &BPFProgAttachAttr{
		AttachType:  unix.BPF_CGROUP_DEVICE,
		TargetFD:    dirFD,
		AttachBPFFD: fd,
		AttachFlags: unix.BPF_F_ALLOW_MULTI,
	}
	if err := BPFProgAttach(attachAttr); err != nil {
		return errors.Wrap(err, "failed to call BPF_PROG_ATTACH (BPF_CGROUP_DEVICE)")
	}
	return nil
}
```

**Comment by lmb** [comment]
You should be able to accomplish the first part using this:

```
prog := NewProgram(&ProgramSpec{
  Type: ebpf.ProgramType(unix.BPF_PROG_TYPE_CGROUP_DEVICE),
  Instructions: insts,
  License: license,
)

fd := prog.FD()
```

I filed #22 for the second part. Maybe it's easiest to just expose `bpfCall()` and `syscallPtr`, but not load prog and associated structure definitions. cc @joestringer what do you think?

**Comment by AkihiroSuda** [comment]
thanks, `bpfCall()` is small enough to copy, so I can close this issue
