### ISSUE TITLE
Marshaling slices/arrays in map keys/values

### ISSUE THREAD

**Issue by rabbitstack** [cilium/ebpf#205]
I have a map that operates on values containing arrays:

```
struct event_descriptor {
    struct param_info params[120];
}
```

I was wondering if it would be possible to marshal the slice of  `param_info` structures from Go and put them on the map.

Thanks.

**Comment by rabbitstack** [comment]
Thanks for a quick response! I'll give this a try.

**Comment by lmb** [comment]
Please reach out on slack if it doesn't work!
