### ISSUE TITLE
Populate program arrays from BTF .values

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#214]
This is an issue to track ongoing work on 'statically' (from ELF) populating map contents using BTF map definitions.

This came up because Cilium makes extensive use tail calls that use `PROG_ARRAY` maps, and manually populating them from userspace would be tedious and error-prone. @lmb came up with the following syntax:

```c
struct {
	__uint(type, BPF_MAP_TYPE_PROG_ARRAY);
	__uint(key_size, sizeof(uint32_t));
	__uint(value_size, sizeof(uint32_t));
	__uint(max_entries, 2);
	__array(values, int (void *));
} prog_arr __section(".maps") = {
	.values = {
		[0] = &xdp_tail_call_1,
		[1] = &xdp_tail_call_2,
	},
};
```

(Note: clang expects anonymous function declarations to be in the format of `return_type (fn_params, ...)`. The `__array` macro just so happens to implicitly take out a pointer to this declaration, so this doesn't need to be done explicitly.)

There is one other example in the kernel's samples ([`map_perf_test_kern.c`](https://github.com/torvalds/linux/blob/master/samples/bpf/map_perf_test_kern.c)) that uses `.values` on an `ARRAY_OF_MAPS`, which we might be interested in using as well. Perhaps we could support `.values` for all map types over time?

**Comment by lmb** [comment]
See also #174 which attempts to add a related feature for nested maps.

**Comment by lmb** [comment]
@anakryiko do you have an opinion regarding this, provided that we can get clang to emit the right relocations, etc.?

**Comment by anakryiko** [comment]
This is something like what I had in mind back when we were just inventing BTF-defined maps. I just never got around to implementing this, as no one really asked. It should be pretty easy now to add this on libbpf side, though.

**Comment by ti-mo** [comment]
@anakryiko Great, thanks for the reply! Does the syntax in the issue description look like something libbpf would go with? With the snippet above, clang emits:
```
Relocation section '.rel.maps' at offset 0xe38 contains 2 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name
0000000000000038  0000002400000001 R_BPF_64_64            0000000000000000 xdp_tail_call_1
0000000000000040  0000002500000001 R_BPF_64_64            0000000000000010 xdp_tail_call_2
```
This looks like enough information to correlate map index with fn pointer. WDYT?

**Comment by anakryiko** [comment]
Yeah. It's very similar in nature to map-in-map support, except for referencing variables you are referencing functions, which from the ELF perspective is about the same thing (still a symbol, just of different type).
