### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#217]
See https://ebpf.semaphoreci.com/workflows/c1feeffb-236c-4597-b12c-17b273a207d1?pipeline_id=5d6022b7-2df9-4a95-9ef0-d7651d400747 for example.

```
Performing shallow clone with depth: 50 00:01
Branch not found performing full clone 00:01
Cloning into 'ebpf'... 00:01
Warning: Permanently added 'github.com,140.82.121.3' (RSA) to the list of known hosts. 00:01
git@github.com: Permission denied (publickey). 00:01
fatal: Could not read from remote repository. 00:01
Please make sure you have the correct access rights 00:01
and the repository exists.
```

Seems like permissions got wonked up. cc @joestringer since you own the OAuth token for the semaphore integration.

**Comment by joestringer** [comment]
Root cause was a mix up with the Cilium organization OAuth settings and an unintended rollback of semaphore-ci authentication rights while testing out new CI functionality for cilium/cilium. This issue is now resolved.
