### ISSUE TITLE
data section .data..percpu: missing size

### ISSUE THREAD

**Issue by mythi** [cilium/ebpf#223]
I'm experimenting with BPF LSM hooks and building my program (hook to `file_ioctl`) using `bpf2go` (clang 11).

With the default `bpf2go` cflags, the kernel refuses to load the program due to `unknown opcode 8d` (I debugged this with `bpftool prog`). [An old bug](https://bugzilla.redhat.com/show_bug.cgi?id=1618958) suggests `-O2` should always be used. 

However, when adding `-cflags "-O2"` to `bpf2go` params, the ELF loads OK with `bpftool prog` but my simple `cilium/ebpf` based Go prog errors with:
`resolve BTF for LSM hook file_ioctl: can't load kernel spec: data section .data..percpu: missing size`.

The error suggests my kernel is faulty but I don't see the error when building without `-O2`.

Any ideas where to look?

Kernel: 5.11, pahole 1.20.

**Comment by mythi** [comment]
> The error suggests my kernel is faulty but I don't see the error when building without -O2.

After thinking this a bit I don't see how these are related. I submitted a PR for add -O2 to default bpf2go cflags and will look into internal/btf parsing test cases using my kernel next.

**Comment by mythi** [comment]
> will look into internal/btf parsing test cases using my kernel next.

```
$ go test -v -run TestParseVmlinux
=== RUN   TestParseVmlinux
    btf_test.go:36: Can't load BTF: data section .data..percpu: missing size
--- FAIL: TestParseVmlinux (0.04s)
FAIL
exit status 1
FAIL	github.com/cilium/ebpf/internal/btf	0.046s
```

**Comment by lmb** [comment]
Which kernel are you testing against? I probably need to update the shipped test vmlinux BTF and see what is going on.

**Comment by mythi** [comment]
@lmb I have 5.11 but also pahole version matters.  AFAIK, pahole v1.18 started percpu values to BTF

**Comment by mythi** [comment]
> I probably need to update the shipped test vmlinux BTF and see what is going on.

I can see if I can fix this. It's a good learning opportunity for BTF internals. I believe [this commit](https://git.kernel.org/pub/scm/devel/pahole/pahole.git/commit/?id=f3d9054ba8ff1df0fc44e507e3a01c0964cabd42) explains what needs to be done.

**Comment by lmb** [comment]
That would be great! Looking at the output in your linked commit it might be enough to only require explicit data section sizes if the size is zero? Basically, skip the rest of the loop if `SizeType != 0` https://github.com/cilium/ebpf/blob/ac42a2b974371d08370945a97a1449801259c01a/internal/btf/btf.go#L325-L330

**Comment by mythi** [comment]
> Basically, skip the rest of the loop if `SizeType != 0`

This seems to be enough indeed!
