### ISSUE TITLE
support for bpf_elf_map 

### ISSUE THREAD

**Issue by sbezverk** [cilium/ebpf#228]
When bpf_elf_map is defined in ebpf c code, like this:
```
struct bpf_elf_map __section("maps") keys = {
    .type = BPF_MAP_TYPE_HASH,
    .size_key = sizeof(struct key),
    .size_value = sizeof(struct hdr),
    .pinning = PIN_OBJECT_NS,
    .max_elem = 1024,
};
```

https://github.com/cilium/ebpf/blob/master/elf_reader.go#L487

fails to parse it with error: `load maps: map {keys 17 0 SHN_UNDEF+8 0 36  }: unknown and non-zero fields in definition`

**Comment by joestringer** [comment]
Hi @sbezverk , would you mind describing what you are trying to achieve at a higher level? This might help folks to suggest solutions to how to write the eBPF for your overall problem, rather than focusing too deeply into implementation details of one particular failure.

**Comment by sbezverk** [comment]
@joestringer 
I have two processes running in different Linux namespaces I load ebpf code in corresponding namespaces and tc monitor running in each namespace show ebpf program gets loaded. It seems with maps is a different story, both processes sees and use the same ebpf map. My goal is that each ebpf instance would be using its own man for communicating with userspace part. I thought specifying `.pinning = PIN_OBJECT_NS` would do the trick and map gets automatically be created in the namespace of the process. Let me know if you need further details.

**Comment by joestringer** [comment]
AFAICT from iproute2 `PIN_OBJECT_NS` feature it basically only changes the filepath that is used for pinning the object, based on an object UID from the ELF. The BPF filesystem is still global, so it's not really mapping to the namespace (but it might happen to separate the maps in a way that is compatible with your use case).

**Comment by sbezverk** [comment]
@joestringer I think you are right, it should work for my use case, now the question is if cilium ebpf library could properly process bpf_elf_map, check if  PIN_OBJECT_NS is on and then create a map not in a default folder.

**Comment by faicker** [comment]
I have the same problem using in tc ebpf, but with the pinning is PIN_GLOBAL_NS.
Is this related to tc struct bpf_elf_map definition in iproute2/bpf_elf.h(different with kernel version)?
should I changed the map definition to like this ?
`
 struct
  {
      __uint(type, BPF_MAP_TYPE_ARRAY);
⤫     __type(key, __u32);
⤫     __type(value, __u64);
      __uint(max_entries, 1);
  } packets SEC(".maps");
`

**Comment by lmb** [comment]
The library follows libbpf formats, so `.pinning` is not supported in "old style" map definitions. You can use BTF definitions however:
https://github.com/cilium/ebpf/blob/0ad18354077124437751e03d302626891096133a/testdata/loader.c#L25-L31

**Comment by ti-mo** [comment]
Some extra context:

`bpf_elf_map` is a structure that is/was supported by the iproute2 BPF loader. I understand iproute2 has recently switched to using libbpf for loading as well, so not sure if this still holds today. It's still used in some kernelspace examples in the 5.11 tree: https://elixir.bootlin.com/linux/v5.11.1/C/ident/bpf_elf_map, though there are no userspace examples anymore..

As @lmb mentioned above, BTF-style map definitions are the way forward as they're much more flexible, and over time they might even support arbitrary keys to be specified to provide some extra info to userspace program.

Alternatively, if you can't/won't use clang>9 with BTF support, this library also supports `struct bpf_map_def` (https://elixir.bootlin.com/linux/v5.11.1/source/tools/lib/bpf/bpf_helpers.h#L108) entries in the legacy `maps` (*not* `.maps`) section.
