### ISSUE TITLE
Iterate .maps datasec directly instead of sec.symbols

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#239]
From https://github.com/cilium/ebpf/pull/218#discussion_r586336080:

> This can happen in a follow up, ultimately I think we should iterate the Datasec directly.
> ```
> $ bpftool btf dump file testdata/loader-clang-11-el.elf
> ...
> [12] VAR 'hash_map' type_id=11, linkage=global-alloc
> [20] VAR 'hash_map2' type_id=19, linkage=global-alloc
> [22] VAR 'btf_pin' type_id=21, linkage=global-alloc
> [52] DATASEC '.maps' size=0 vlen=3
> 	type_id=12 offset=0 size=40
> 	type_id=20 offset=0 size=32
> 	type_id=22 offset=0 size=40
>```
> So instead of looping over sec.symbols try to FindType(secName, &btf.Datasec) and then iterate Datasec.Vars. That gives us access to VarSecinfo.Offset and VarSecinfo.Size which we'll need when trying to match relocations against the maps section.
>
> Aside: kind of weird that offset=0 in the dump, I wonder what's up with that.

**Comment by mmat11** [comment]
Closing the issue -> https://github.com/cilium/ebpf/pull/267
