### ISSUE TITLE
loading a program using constants as a non-root user returns "operation not permitted"

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#244]
An example is a socketfilter that uses constants like https://github.com/cloudflare/rakelimit.

```
program filter_ipv4: map .rodata: can't freeze map: can't freeze map: operation not permitted
```

* Why doesn't the kernel let us freeze the map?
* Can we ignore EPERM during freezing? After all we already check whether we can freeze in the first place.

**Comment by rgo3** [comment]
Hi, I'd be interested in working on this as it is marked a `good-first-issue`. Any pointers towards how I could reproduce it or a hint on how to get started?

**Comment by lmb** [comment]
To reproduce, clone `rakelimit` at this branch: https://github.com/cloudflare/rakelimit/pull/22

```
go test -v -exec 'strace -f -e trace=bpf' -run TestAttackPropagation
```

That should give you:
```
generalisation_test.go:393: Can't create limiter: load BPF: field FilterIpv4: program filter_ipv4: map .rodata: can't freeze map: can't freeze map: operation not permitted
```

Plus a bunch of syscall traces, among which is the reason for the error:
```
[pid 59981] bpf(BPF_MAP_FREEZE, {map_fd=7}, 4) = -1 EPERM (Operation not permitted)
```

The error originates here: https://github.com/cilium/ebpf/blob/2e76685ddb33660f5cc13955b796d0e53d2ea662/map.go#L346-L348

There are two options: we're doing something wrong and get EPERM for that reason, or freezing a map is a privileged operation (which is surprising). So it would be good to verify why we get EPERM in the first place, by looking at the kernel source.

A work around is to check whether we get `EPERM` from map.Freeze in the library and continue as if nothing happened in that case. This would be a bit of a bummer though, since freezing is useful to unprivileged programs as well.

**Comment by rgo3** [comment]
So I was able to reproduce and spent some time going through the kernel code.

Arrived here: 
https://github.com/torvalds/linux/blob/7d6beb71da3cc033649d641e1e608713b8220290/include/linux/capability.h#L262

That gets called from the syscall I think:
https://github.com/torvalds/linux/blob/e767b3530acbf651593e3d357fe1168a024d8061/kernel/bpf/syscall.c#L1562

I'm not to familiar with capabilities in Linux except for looking at the manpage right now... guessing the test fails as the process does not have the `CAP_BPF` capability? I'll try to figure it out by playing with capabilities a bit.

**Comment by rgo3** [comment]
Ok. By "as if nothing happened" you mean ignoring the permission error? I haven't used this library myself, but from a user perspective isn't this misleading to silently allow freezing while the kernel won't actually freeze the map?

**Comment by lmb** [comment]
Good point, there are two distinct use cases:
1. Explicit calls to Map.Freeze. Here we should return all errors as they are.
2. Calls done by the library as part of map set up (this is the one I linked). Here we should attempt to freeze, and ignore EPERM.

In the second case the user doesn't have a way to ask the library to not freeze.

**Comment by rgo3** [comment]
Ok, yes I would have added another `if` statement to the map.Freeze call in the map setup code you linked. Should there be some sort of log line/warning in case we get EPERM?

**Comment by borkmann** [comment]
> 2. Calls done by the library as part of map set up (this is the one I linked). Here we should attempt to freeze, and ignore EPERM.

If this is a map for `.rodata`, the loader should probably bail out if it cannot freeze it. I didn't follow the whole conversation, do you have a clear use case for unpriv?

**Comment by lmb** [comment]
Yes, this is for `.rodata`, used by this constant here: https://github.com/cloudflare/rakelimit/blob/master/src/rakelimit.c#L15 I figured that the worst that can come from a failed freeze is worse performance (due to missed constant inlining by the verifier). Is there something else that makes this dangerous?

> Probably worth investigating to allow for unpriv if rakelimit is a first user.
That would be great! @rgo3 is this in scope of your GSoC?

> Should there be some sort of log line/warning in case we get EPERM?
The library doesn't log itself, we'd have to put something in an `error` instead. Let's see whether this is "safe" in the first place.

**Comment by rgo3** [comment]
At the moment there is no clear scope for my GSoC yet. I was planning on doing a proposal about this https://github.com/cilium/cilium/issues/11014 here (probably the solution that would involve implementing a feature probe API in cilium/ebpf) which is unrelated to the current issue. But I need a PR to apply for a GSoC with cilium which is why I am here.

But related or not, happy to help investigating if I can! I will ask on slack if this can count towards a GSoC proposal though because otherwise I'll also have to find something for that too.

**Comment by lmb** [comment]
OK.

I realised why this won't be as straight forward: if you add the work around I suggested you'll probably find that the kernel rejects the program, since the `.rodata` map doesn't have type info (aka BTF) attached to it. That in turn happens because BTF isn't available to unprivileged programs. So fixing this in the kernel might be a good chunk of work.

**Comment by rgo3** [comment]
Ok theres definitely some stuff in your message I'm not familiar with yet.. I also have no kernel contributions yet, so a complicated one seems even more intimidating :grimacing:.

I interpreted @borkmann's message earlier like we could investigate whether freezing has to be a privileged operation in the first place? Would changing that, if possible also be a bigger project?

**Comment by lmb** [comment]
Here is what has to happen behind the scenes for constants to work:

```
btf = bpf_load_btf(...)
rodata = bpf_map_create(..., btf)
bpf_map_freeze(rodata)
bpf_prog_load(..., rodata)
```

BTF is essentially metadata, see https://www.kernel.org/doc/html/latest/bpf/btf.html

The library currently does the following:

```
btf = bpf_load_btf(...) // returns EPERM, ignored
rodata = bpf_map_create(...) // without BTF, due to earlier EPERM!
bpf_map_freeze(rodata) // returns EPERM, causes the error described here
bpf_prog_load(..., rodata) // we don't get here
```

I initially assumed that we can fix the error by ignoring EPERM from bpf_map_freeze. If you do that, I suspect you will see that bpf_prog_load (that we don't get to) will also return an error of some sort. This error is likely because we loaded the map without BTF.

So: allowing bpf_map_freeze is probably a simple change. However, it doesn't allow using constants from an unprivileged user, since that requires being able to load BTF. Making BTF available for unprivileged users is a much bigger problem. @borkmann will know whether it's feasible at all.

**Comment by rgo3** [comment]
Thanks for the details @lmb, gave me some points to look for in the library as well as kernel code. I was a little hung up on the map freezing part and got confused.

If I understand correctly there isn't really anything I can help with at the moment, so I'll just keep an eye on this issue in case there will be something I can help with.

**Comment by lmb** [comment]
There isn't much we can do on the library side, closing.
