### ISSUE TITLE
Add per-CPU Map Support to Batch Operations

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/ebpf#251]
Currently, batch operations do not support per-CPU maps. This is not a technically difficult thing to accomplish, but deciding on the right interface within the library presents some challenges. [See this previous PR](https://github.com/cilium/ebpf/pull/229) attempt for details.

**Comment by brycekahle** [comment]
This may be handled already, but I noticed this when reading the commits for batch operations:
> value_size must be aligned to 8 bytes by userspace if it's dealing with percpu maps

**Comment by ti-mo** [comment]
I don't think our batch API supports per-cpu ops yet. Does the kernel API even support it?

**Comment by brycekahle** [comment]
> I don't think our batch API supports per-cpu ops yet.

It doesn't, that is what this issue is for 😄 . I was just adding a helpful note for future implementers.

**Comment by romanmendelproject** [comment]
Is this functionality really needed!
