### ISSUE TITLE
Support passing a custom BTF file

### ISSUE THREAD

**Issue by ungureanuvladvictor** [cilium/ebpf#254]
While using the library I realized that the kernel which I have on my host (`5.4.0-1037-aws`) does not have BTF support enabled out of the box. Would be good the the library to support loading an out of band compiled BTF file if the kernel does not come with one. While talking with @lmb on Slack one suggestion is to plumb this through `CollectionOptions`.

**Comment by ti-mo** [comment]
Agreed, this would be nice to have. Could you elaborate on the specific use case for anyone that would want to pick this up?
The library already looks for [vmlinux binaries at specific locations](https://github.com/cilium/ebpf/blob/51e8795c0392b05fee83dde1d2dad7aafeae2800/internal/btf/btf.go#L216-L233), but I expect you're already aware of that.

What would the distribution format look like? Something like `vmlinux-btf.gz`?

**Comment by lmb** [comment]
API design question: do we take a path to a BTF file, or an io.Reader or maybe even a `*btf.Spec`? The last option would require moving `internal/btf` so that it's exported.

**Comment by ungureanuvladvictor** [comment]
@ti-mo -- I am aware of the specific paths for BTF files but the thing I had in mind is if I use `cilium/ebpf` (on a non BTF generated kernel) in a container that is deploy then I'd have to mount the file at one of those locations and it gets a bit weird (not to say that is is impossible).

**Comment by ti-mo** [comment]
@ungureanuvladvictor Indeed, containerizing the binary defeats the path searcher, hadn't thought of that. Theoretically it could be possible to mount a file from a ConfigMap at `/sys/kernel/btf/vmlinux`, have you tried that before?

@lmb 
- path to a BTF file -> requires the caller to write a file to disk, which might not always be desired (e.g. containers with read-only fs)
- an io.Reader -> sounds like the ideal middle ground; caller can pull in the BTF blob from anywhere. Disk, metadata service, even directly from k8s API.
- a *btf.Spec -> as you indicated, this will involve some work, and might not be the best move for this particular feature

**Comment by ungureanuvladvictor** [comment]
@ti-mo I did not try to mount things inside the container fs because @lmb mentioned to me that core support is stalled so did not pursue that path more.

**Comment by lmb** [comment]
The bind mount seems like a good work around. Seems like we agree that a dedicated option would be good however.

I'd start by adding `TargetBTF io.Reader` to https://pkg.go.dev/github.com/cilium/ebpf#ProgramOptions and plumb that through to the BTF package.

Open questions:
* We might need `io.ReaderAt` instead of `io.Reader`
* Does MapOptions need a `TargetBTF` as well?
* If MapOptions needs TargetBTF, how do we avoid parsing BTF multiple times? (This is where `Target *btf.Spec` is better.)
