### ISSUE TITLE
pinning an object for the first time can return EEXIST

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#263]
Assuming that `/foo/bar` is a pinned program on a bpffs:

```
prog := NewProgram()
prog.Pin("/foo/bar") // returns EEXIST
```

Compare this to what happens when the program is already pinned elsewhere:

```
prog := NewProgram()
prog.Pin("/foo/baz")
prog.Pin("/foo/bar") // returns nil
```

This is because we call os.Rename behind the scenes in the latter case. I'm not sure what the correct behaviour is but I think that the current behaviour is surprising and we should do something about it.

I realised the implementation has another corner case: os.Rename will return `EXDEV` if the old and new path don't reside on the same file system.

Some testcases which show the problem in detail:

```
func TestProgramPinExisting(t *testing.T) {
	prog := createSocketFilter(t)
	tmp := tempBPFFS(t)

	path := filepath.Join(tmp, "program")
	if err := prog.Pin(path); err != nil {
		t.Fatal(err)
	}

	prog2, err := prog.Clone()
	if err != nil {
		t.Fatal(err)
	}

	if err := prog2.Pin(path); err != nil {
		t.Fatal("Can't override existing pin:", err)
	}
}

func TestProgramPinRenameExisting(t *testing.T) {
	prog := createSocketFilter(t)
	tmp := tempBPFFS(t)

	path := filepath.Join(tmp, "program")
	if err := prog.Pin(path); err != nil {
		t.Fatal(err)
	}

	prog2, err := prog.Clone()
	if err != nil {
		t.Fatal(err)
	}

	if err := prog2.Pin(filepath.Join(tmp, "prog2")); err != nil {
		t.Fatal(err)
	}
	if err := prog2.Pin(path); err != nil {
		t.Fatal("Can't override existing pin:", err)
	}
}
```

**Comment by lmb** [comment]
cc @aditighag

**Comment by lmb** [comment]
I think we should document that moving a pin across filesystems is not supported, since I don't see a use case for it.

As for the EEXIST behaviour: being able to override a pin atomically is useful when upgrading pinned state (which is how I hit this problem). However, making this the default behaviour seems a bit risky, overwriting should be opt in. So for the purposes of this bug I think we should call `renameat2` with `RENAME_NOREPLACE` which would bring the second case in line with the first one.
From a quick glance at the kernel source it seems like bpf should support this flag since 4.9: https://github.com/torvalds/linux/commit/e0e0be8a835520e2f7c89f214dfda570922a1b90

Overwriting can be done via an option to `Pin` at some other stage.

**Comment by aditighag** [comment]
Interesting find! 

>for the purposes of this bug I think we should call renameat2 with RENAME_NOREPLACE

Does Go expose an API to rename without replace? From a cursory search, I found this - [1]. However, the syntax of renameat2 [2] seems a bit more elaborate. Have you looked at whether we'll still have atomicity if we were to call this syscall?

Alternatively, how about we check if the new Path exists on the file system before calling `os.Rename`? We lose atomicity with this approach if file system state changes between the two calls. 

[1] https://pkg.go.dev/golang.org/x/sys/unix#Renameat2
[2] https://man7.org/linux/man-pages/man2/renameat2.2.html

**Comment by lmb** [comment]
> Have you looked at whether we'll still have atomicity if we were to call this syscall?

From the man page you linked it looks like it:
```
If newpath already exists, it will be atomically replaced, so
that there is no point at which another process attempting to
access newpath will find it missing.
```

I suspect that os.Rename ends up calling renameat behind the scenes anyways. I'd prefer calling renameat2 directly to prevent the race condition you mention. We can pass `unix.AT_FDCWD` for olddirfd and newdirfd which should make the invocation straight forward.

**Comment by aditighag** [comment]
Re: atomicity
I was referring to the other two directory related arguments that are passed `renameat2`.

I can try to fix this, unless you are already working on it.

**Comment by lmb** [comment]
> I can try to fix this, unless you are already working on it.

That would be great, I've not tackled this!

> I was referring to the other two directory related arguments that are passed renameat2.

I think we need something like this:

```
unix.Renameat2(unix.AT_FDCWD, currentPath, unix.AT_FDCWD, newPath, unix.RENAME_NOREPLACE)
```

unix.AT_FDCWD is a magic constant described on https://man7.org/linux/man-pages/man2/renameat2.2.html Does that help?

**Comment by lmb** [comment]
@aditighag do you have time to take a stab at this? I'd like to do a bugfix release before too many commits pile up in master.

**Comment by aditighag** [comment]
Yup, I haven't forgotten. I'll send out a PR some time this week.
