### ISSUE TITLE
parse retprobe bit position from sysfs

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#275]
We have a TODO in the kprobe code:

https://github.com/cilium/ebpf/blob/2ef3f386b3d550ba605dee0f783a625f1f14c029/link/kprobe.go#L120

Doesn't sound too complicated, maybe this is a good first issue @ti-mo ?

**Comment by ti-mo** [comment]
Thanks, absolutely! libbpf code is here: https://github.com/torvalds/linux/blob/8f3f5792f2940c16ab63c614b26494c8689c9c1e/tools/lib/bpf/libbpf.c#L9608-L9620
