### ISSUE TITLE
pmu uprobes are broken

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#292]
@ti-mo @lmb FYI pmu uprobes are broken; they were working before doing some refactoring. I suppose it's the offset not being passed correctly to `perf_event_open`:

```
$ sudo bpftool perf
pid 1056229  fd 3: prog_id 712  uretprobe  filename /bin/bash  offset 0
```
I am continuing to debug.

PS. currently I believe there aren't "e2e" tests, are these planned?

_Originally posted by @mmat11 in https://github.com/cilium/ebpf/issues/280#issuecomment-824230882_

**Comment by ti-mo** [comment]
@ungureanuvladvictor pointed me to the fact that the uprobe example works on Ubuntu's build of Bash (including 21.04), and I found that Ubuntu ships with a statically-linked version of `readline`. It looks like they vendor a version of readline in the Bash tree, but it can optionally be linked against `libreadline.so`:
```
~ objdump -T /bin/bash
00000000000ad900 g    DF .text  0000000000000088  Base        readline
```

On my system (Arch), readline is provided by `libreadline.so`:
```
λ  ~  objdump -T /bin/bash | grep readline
0000000000000000      DF *UND*	0000000000000000              readline
```

The 0 offset as parsed by `debug/elf` is correct, this symbol is to be provided by a library and still needs to be relocated. This means we'll either need to find or implement a dynamic linker in Go, and allow the caller to pass in their own offsets for now. Will close this with a PR to disable creating Uprobes from symbols from SHN_UNDEF with offset 0.
