### ISSUE TITLE
Uprobe - support tracing shared library calls

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#297]
See https://github.com/cilium/ebpf/issues/292 for the backstory.

Currently, the library does not support attaching uprobes to symbols that are provided by shared objects (libraries). To remove this limitation, we could:
- Allow the caller to provide a uprobe symbol offset manually:
  + `ex.UprobeOffset(0x123, prog)`
  + `ex.Uprobe("readline", prog, &UprobeOptions{Offset: 0x123})`
  + Other suggestions?
- Implement a part of ld-linux in Go that can resolve the correct offsets. I hear BCC does this, maybe it can be considered if it's not too complicated (unlikely). 
- Leave it as it is and don't implement it.
- Other suggestions?

**Comment by mmat11** [comment]
IMO, 1 seems to be a good compromise, maybe the options part should be part of `Executable`, not `Uprobe`/`Uretprobe`.

My suggestion for option 1:
`OpenExecutable(path, ...Symbol)`

Symbol is a struct containing name and offset. All the provided symbols will be then stored in a map that will have higher priority when fetching the offset by name in the `symbol()` method.

**Comment by lmb** [comment]
> All the provided symbols will be then stored in a map that will have higher priority when fetching the offset by name in the symbol() method.

Seems a bit complicated to me. What is the benefit of this vs. just taking an address?

> Other suggestions?

Do we have examples of someone doing this in the wild? @brycekahle maybe?

**Comment by mmat11** [comment]
> Seems a bit complicated to me. What is the benefit of this vs. just taking an address?

The offset has to be specified once in case of multiple probes for the same symbol. The implementation can be simplified (eg. overwrite the symbol in the symbols map), but I agree that the api is not the best

**Comment by brycekahle** [comment]
> Do we have examples of someone doing this in the wild?

We aren't using uprobes at the moment, but it is something we will likely be doing in the near future.

IMO it is probably best to start with the most straightforward approach of providing the offset.
