### ISSUE TITLE
BPF ring buffer

### ISSUE THREAD

**Issue by mythi** [cilium/ebpf#316]
I've started working on adding support for BPF ring buffer that was added in Linux 5.8. Here's my changes so far:

- [ ] updated types.go
- [ ] updated asm/func.go
- [ ] similar to `perf`, added `ringbuf` package

A lot of the code from `perf` can be re-used but haven't yet figured out which parts could be shared. Would a new package `ringbuf` make sense?

**Comment by ti-mo** [comment]
Thanks for the patch! I'm not very familiar with the current perf ringbuf implementation, but I would indeed assume they could share some primitives. It might even make sense to put perf and BPF ringbuf behind the same API, otherwise it might become hard to navigate.

@lmb

**Comment by glennWang** [comment]
Could add a demo about using XSKMap ? Include umem, FILL ring, COMPLETION ring, RX ring, TX ring.

**Comment by kolinfluence** [comment]
@mythi @lmb possible to show an example message passing between ebpf c and golang program between them? i tried to do so with chatgpt help but it's not working on ubuntu 22.04.

can you pls provide an example for use?

**Comment by lmb** [comment]
@kolinfluence are you the same person as https://github.com/ouvaa ?

**Comment by ti-mo** [comment]
@kolinfluence This is the issue tracker, not a forum to ask questions. Please look at the examples folder: https://github.com/cilium/ebpf/tree/main/examples/ringbuffer, that should do what you need.
