### ISSUE TITLE
Tag a 0.6.1 release

### ISSUE THREAD

**Issue by kolyshkin** [cilium/ebpf#323]
PR #320 was recently merged to help with issue in runc, so runc now vendors the updated version (https://github.com/opencontainers/runc/pull/3009).

The only concern is we're now vendoring by sha, rather than using a tag.

Is it possible to tag a minor release (I guess `v0.6.1`) so that runc can use it? 🙏🏻 

Cc // @lmb @ti-mo

**Comment by ti-mo** [comment]
I've tagged [v0.6.1](https://github.com/cilium/ebpf/releases/tag/v0.6.1), will create release notes briefly.
