### ISSUE TITLE
The difference between MapSpec and MapABI is unclear

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#33]
See #30, #26 and probably others. The difference between MapABI and MapSpec isn't entirely obvious. Either we get rid of MapABI somehow, or we document the differences.

One possibility is to make the fields in MapABI public in Map, so users could access Map.Type, etc. This creates the opportunity for race conditions however, so I'm not a big fan.

Maybe there is also a better name for MapABI (and friends).

**Comment by nathanjsweet** [comment]
What about making MapABI an interface of which MapSpec can be an implementor?

**Comment by lmb** [comment]
Thanks for reminding me to give this some more thought.

Users try to use MapABI and end up frustrated, because it doesn't expose the information they want. MapABI doesn't expose them because the library has to be consistent across the supported kernels, which includes 4.9. On 4.9 we can't get more information that what is in MapABI currently.

I think the solution to this is to introduce something like `MapInfo`: this encapsulates metadata about a loaded map from the kernel. This isn't the same as a MapSpec, which contains metadata needed to create a map. On recent kernels it's probably possible to create a MapSpec from a MapInfo, but on older ones this isn't true.

The biggest hurdle to `MapInfo` is how to expose "optional" metadata: things that are not available on all supported kernels. One idea was to just use pointers for those:
```
type MapInfo struct{
    KeySize uint32
    ...
    SomeOtherField *uint32
}
```
Once MapInfo exists we could unexport or remove MapABI.
