### ISSUE TITLE
TCP Check sum modification error in eBPF egress.

### ISSUE THREAD

**Issue by dhawaskar** [cilium/ebpf#337]
Hi,

I am trying to modify the TCP csum in TC-eBPF at egress. As first step, I computed the csum myself and write into the tcp csum field.But in wire shark, the csum field in TCP is not modified instead it is original value. That is the pseudo header checksum from the Linux kernel.

I need to append the new payload to the beginning of the TCP payload and hence I started this as my initial step.

I tried writing the check using the pointer,using strore_bytes and l4_replace and none of the methods work. I have listed all API in the code below. I used all API once and one by one,nothing seems to work.
Below is the code:
//Compute the checksum
	  int offset=ethl+iphl;
		__u32  rbuf;
		__u8 bufleft8;
		__u16 bufleft16;
		__u64 sum = 0;
		__u16 csum=0;
		
		int i=0;
		#pragma unroll
		for (i=0;i<375;i+=4){//256
			if(data+offset+i+1>data_end){
				char msg[]="sandy data offset is beyond access point \n";
				bpf_trace_printk(msg, sizeof(msg));
				break;
			}
			bpf_skb_load_bytes(skb,offset+i,&rbuf,sizeof(rbuf));
			char msg1[]="sandy data red: %x \n";
			bpf_trace_printk(msg1, sizeof(msg1),bpf_ntohl(rbuf));
			sum += rbuf;
			
		}
		if(payload_length%4>0){
				int leftbytes=(payload_length%4);
				switch(leftbytes){
					case 1:	bpf_skb_load_bytes(skb,skb->len-1,&bufleft8,1);
								 	char msg1[]="sandy data left: %x \n";
									bpf_trace_printk(msg1, sizeof(msg1),bufleft8);
									sum += bufleft8;
									break;
					case 2:	bpf_skb_load_bytes(skb,skb->len-2,&bufleft16,2);
								 	char msg2[]="sandy data left: %x \n";
									bpf_trace_printk(msg2, sizeof(msg2),bufleft16);
									sum += bufleft16;
									break;
					case 3:	bpf_skb_load_bytes(skb,skb->len-3,&bufleft16,2);
								 	char msg3[]="sandy data left: %x \n";
									bpf_trace_printk(msg3, sizeof(msg3),bufleft16);
									sum += bufleft16;
									bpf_skb_load_bytes(skb,skb->len-1,&bufleft8,1);
								 	char msg4[]="sandy data left: %x \n";
									bpf_trace_printk(msg4, sizeof(msg4),bufleft8);
									sum += bufleft8;
									break;			
				}
		}

 sum = (sum >> 32) + (sum & 0xFFFFFFFF); // Fold into 32 bits
	sum = (sum >> 32) + (sum & 0xFFFFFFFF); 
	sum = (sum >> 16) + (sum & 0xFFFF); // Fold into 16 bits
	sum = (sum >> 16) + (sum & 0xFFFF);

csum=~sum;
    tcphp->check=csum;//method 1
  	offset=ethl+iphl+16;
		ret = bpf_skb_store_bytes(skb, (int)offset, &csum, sizeof(csum),//method 2
                            BPF_F_RECOMPUTE_CSUM);
		if(!ret){
			char msg[]="sandy csum written: %x\n";
     	bpf_trace_printk(msg, sizeof(msg),bpf_ntohs(csum));
		}

ret=bpf_skb_load_bytes(skb,offset,&error_csum,2);
  	if(!ret){
  		char msg[]="sandy red error csum: %x \n";
    	bpf_trace_printk(msg, sizeof(msg),bpf_ntohs(error_csum));//This gives write csum values.
  	}

bpf_l4_csum_replace(skb,ethl+iphl+16,old_checksum,csum,BPF_F_PSEUDO_HDR|2);//method 3

Now when I check the trace_pipe in Linux I see the value being modified but in wire shark it shows the original value from kernel  . Hence at receiver the packets are dropped even my checksum value computed is correct.

Could anyone please fix this or suggest if I am doing anything wrong.  

Thanks
Sandesh

**Comment by lmb** [comment]
This is most likely an interaction of your program with the network stack. Please ask around in the ebpf slack: https://ebpf.io/slack

I'm closing this issue since it's not related to the library per se.

**Comment by dhawaskar** [comment]
Hi,

This is the problem in 4.17 kernel in >5.4.X, I cannot even access the payload. Details below.I did posted in eBPF slack have not got anything yet.
I am doing TC-eBPF programming for my research.
I am using the “bpf_skb_adjust_room” API in TC-eBPF to append to the TCP payload (I need to append to the beginning of the payload, not at the end, so bpf_skb_adjust_room is only option I have).
I can see my packets at the receiver but checksum computation for TCP is wrong and packets are dropped.
The reason for the checksum update failing is because of API “bpf_skb_adjust_room”. The checksum of TCP at TC-eBPF level has only pseudo header checksum. The TCP header and payload checksum is computed below the TC-eBPF level at NIC driver . Once “bpf_skb_adjust_room” is called, the checksum update in net driver level doesn’t happen and it is kept as a pseudo header checksum. Hence the packets are dropped at the receiver as checksum is not updated. In https://man7.org/linux/man-pages/man7/BPF-HELPERS.7.html “BPF_F_ADJ_ROOM_NO_CSUM_RESET” is said to be used with “bpf_skb_adjust_room” flag to avoid reset of the checksum at net driver. I tested this flag in kernel 5.4.x to 5.12.x and the flag does nothing. 
The only solution for this is to compute the complete TCP checksum(pseudo+header+payload). But there is no support to do this in TC-eBPF as a maximum of 512 bytes are allowed and header length ,payload length is variable and not static for TCP. I cannot run the loops without static length fields in TC-eBPF.
Another problem that happens to recompute the checksum is :  cannot access the payload in TC-eBPF level.
skb->length is greater than the (skb->data_end-skb->data) and “bpf_skb_pull_data” API does not do the job. Verified in kernel > 5.4.X. 
Below is the code snippet:
Fix the ipv4 header length and checksum
#define INTMETAHEAD 36
__u16 old_length=bpf_htons(bpf_ntohs(iph.tot_len));
__u16 new_length=bpf_htons(bpf_ntohs(iph.tot_len)+INTMETAHEAD);
bpf_skb_store_bytes(skb, ethl+2, &new_length, 2,BPF_F_RECOMPUTE_CSUM);
bpf_l3_csum_replace(skb,ethl+10,old_length,new_length,2);
Extend the room space after Ipv4 header and pull the TCP header up.
bpf_skb_adjust_room(skb, INTMETAHEAD, BPF_ADJ_ROOM_NET,0);
offset = sizeof(struct ethhdr) + (unsigned long)iphl;
ret=bpf_skb_store_bytes(skb, (int)offset, &tcph,sizeof(tcph),0);
//BPF_F_RECOMPUTE_CSUM this flag does nothing
#add to the beginning of the payload now
offset = ethl+iphl+tcph_len;
if((void *)data+offset+1>data_end){
    Return 0;
}
bpf_skb_store_bytes(skb, (int)offset, &shim,INTMETAHEAD,0); 
If anyone could suggest to me the way to deal with TCP checksum using   “bpf_skb_adjust_room” would be of great help. Else There should be a Linux kernel fix for this.
Thanks
