### ISSUE TITLE
Tag a 0.6.2 release

### ISSUE THREAD

**Issue by kolyshkin** [cilium/ebpf#340]
PR #336 was recently merged to help with issue in runc, so runc now vendors the updated version (opencontainers/runc#3055).

The only concern is we're now vendoring by a sha, rather than using a tag.

Is it possible to tag a minor release (I guess v0.6.2) so that runc can use it? 🙏🏻

Cc // @lmb @ti-mo

**Comment by lmb** [comment]
Timo came back from time off, so I want to give him some time to catch up before tagging a release.

Is there a downside to using a hash vs. a tag?

**Comment by ti-mo** [comment]
No objections for tagging 0.6.2 here, hopefully the error propagation story is now in a good enough shape so this type of issue doesn't occur in the future anymore. :+1:

**Comment by kolyshkin** [comment]
> Is there a downside to using a hash vs. a tag?

Not much really; a hash may not feel kosher, and a tag is perceived more like a commitment ("yes, this functionality is included in version x.y.z"). Surely we are OK with a hash, if having a release cut is problematic.

**Comment by ti-mo** [comment]
We've released https://github.com/cilium/ebpf/releases/tag/v0.6.2 today, closing this.
