### ISSUE TITLE
How to load eBPF_TC on net dev with cilium/ebpf + vishvananda/netlink ?

### ISSUE THREAD

**Issue by glennWang** [cilium/ebpf#353]

**Comment by glennWang** [comment]
solved

**Comment by nimrodshn** [comment]
Any instructions?

**Comment by nimrodshn** [comment]
For those looking for code snippet to create load a TC program using eBPF + netlink please see https://github.com/glenn-wang/ship-xdp-tc-with-go/blob/436c84b0e9a1216fee1049fb525a6c7805435e23/main.go#L61-L114
