### ISSUE TITLE
Uprobe symbol error

### ISSUE THREAD

**Issue by hyunsooda** [cilium/ebpf#358]
Hi all, I followed [Uprobe example](https://github.com/cilium/ebpf/tree/master/examples/uretprobe), and it worked well. However, an error that says can't find the given symbol when I change the binary and symbol. I have explicitly exported symbols to be hooked at compile time (```--export-dynamic```).

My test program is pretty simple.
```
void abc(int x) {}
int main() { abc(10); }
```
After compilation, I could check the function ```abc``` was visible via ```nm``` command.

Besides this problem, I'd like to ask some basic things:
1. I'm guessing that a symbol in the target binary should be visible, is it right? If so, why?
2. Is there an exact specification or description about binary and symbol? there seems no document on how to install Uprobe or Uretprobe.

Thank you

**Comment by ti-mo** [comment]
Hi @hyunsooda, thanks for trying out the uprobe stuff. Know that this feature is still quite fresh, and that we're currently limited in what we can do from Go regarding parsing application binaries.

First off, the descriptions you provide are rather vague, please be as specific as possible and include the original error messages, otherwise we have no way of knowing what you're running into.

If I understand correctly, `nm` doesn't operate on `strip`ped binaries. Most binaries shipped with distributions are stripped, so the library does not rely on debug information being present.

```
λ  ~  nm /bin/bash
nm: /bin/bash: no symbols
```

Rather, the library parses the ELF dynamic symbol table, visible using `objdump`:
```
λ  ~  objdump -T /bin/bash | head -n6

/bin/bash:     file format elf64-x86-64

DYNAMIC SYMBOL TABLE:
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 endgrent
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.3   __ctype_toupper_loc
```

What is the error you're facing? Could you provide a full source code example including how you invoke the compiler? If a function symbol is missing, it could mean it's been inlined. The function in your example is empty, so it could've been optimized away, although I don't see that behaviour here.

For clang, `clang -Wl,--export-dynamic foo.c` seems to emit dynamic symbols correctly. Without `-Wl,--export-dynamic`, it doesn't.

For gcc, `gcc foo.c -export-dynamic -o foo` works as expected with the `-export-dynamic` flag.

Regarding your questions:
> I'm guessing that a symbol in the target binary should be visible, is it right? If so, why?

The kernel's uprobe API traps specific instruction offsets, the kernel is not aware of the layout of your executable. In order for the library to obtain the offset of a (named) function, it needs to parse your application's ELF binary and extract this information, to then pass to the kernel when creating the uprobe.

> Is there an exact specification or description about binary and symbol?

I don't know what you mean by this.

> there seems no document on how to install Uprobe or Uretprobe.

What do you mean by 'install'? Currently, there's no documentation site for the library. For a high-level overview, there's https://pkg.go.dev/github.com/cilium/ebpf, and you've already found `examples/`. This will likely expand in the future.

cc @mmat11

**Comment by hyunsooda** [comment]
Hi @ti-mo, sorry for confusion.

>there seems no document on how to install Uprobe or Uretprobe.

I meant "install" as "trap". 

>Is there an exact specification or description about binary and symbol?

I meant whether there is some documentation about basic knowledge to write some code at least. You answered right above it.

>If I understand correctly, nm doesn't operate on stripped binaries

```nm``` has an option that prints dynamic symbols like ```nm -D ...```.


I have a simple program here:
```
#include <stdio.h>

int foo(long long int x, long long int y) {
    return x + y;
}

int main() {
    int a = foo(100,200);

    printf("%d\n",a);
}
```
I first compiled with this command ```clang-8 test.c -Wl,--export-dynamic -o simpleapp```. The function ```foo```  was exported but it occurs an error. When I compiled with gcc, It worked without error. 

Can I ask one question more If I don't bother you?
I tried to write my first HelloWorld as a printing parameter of function by hooking using eBPF. I changed some code in [Uprobe example](https://github.com/cilium/ebpf/tree/master/examples/uretprobe)
Let me show you the changes.

**main.go**
``` go
diff --git a/examples/uretprobe/main.go b/examples/uretprobe/main.go
index bcd682c..aad4fb7 100644
--- a/examples/uretprobe/main.go
+++ b/examples/uretprobe/main.go
@@ -8,6 +8,7 @@ package main
 import (
        "bytes"
        "encoding/binary"
+       "fmt"
        "log"
        "os"
        "os/signal"
@@ -18,7 +19,7 @@ import (
        "golang.org/x/sys/unix"
 )

-//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang-11 UretProbeExample ./bpf/uretprobe_example.c -- -I../headers -O2
+//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang-10 UretProbeExample ./bpf/uretprobe_example.c -- -I../headers -O2

 // An Event represents a perf event sent to userspace from the eBPF program
 // running in the kernel. Note that this must match the C event_t structure,
@@ -26,6 +27,7 @@ import (
 type Event struct {
        PID  uint32
        Line [80]byte
+       Arg1 uint32
 }

 const (
@@ -34,8 +36,8 @@ const (
        // dynamically-linked library, so the path of the library will need
        // to be specified instead, e.g. /usr/lib/libreadline.so.8.
        // Use `ldd /bin/bash` to find these paths.
-       binPath = "/bin/bash"
-       symbol  = "readline"
+       binPath = "./simpleapp"
+       symbol  = "foo"
 )

 func main() {
@@ -65,7 +67,7 @@ func main() {

        // Open a Uretprobe at the exit point of the symbol and attach
        // the pre-compiled eBPF program to it.
-       up, err := ex.Uretprobe(symbol, objs.UretprobeBashReadline)
+       up, err := ex.Uprobe(symbol, objs.UretprobeBashReadline)
        if err != nil {
                log.Fatalf("creating uretprobe: %s", err)
        }
@@ -113,6 +115,7 @@ func main() {
                        continue
                }

-               log.Printf("%s:%s return value: %s", binPath, symbol, unix.ByteSliceToString(event.Line[:]))
+               //log.Printf("%s:%s return value: %s", binPath, symbol, unix.ByteSliceToString(event.Line[:]))
+               fmt.Println(event.Arg1)
        }
 }
```

**bpf/uretprobe_example.c**
``` go
diff --git a/examples/uretprobe/bpf/uretprobe_example.c b/examples/uretprobe/bpf/uretprobe_example.c
index 94766ea..fa2fe2b 100644
--- a/examples/uretprobe/bpf/uretprobe_example.c
+++ b/examples/uretprobe/bpf/uretprobe_example.c
@@ -6,6 +6,7 @@ char __license[] SEC("license") = "Dual MIT/GPL";
 struct event_t {
        u32 pid;
        char str[80];
+       int arg1;
 };

 struct {
@@ -13,12 +14,15 @@ struct {
 } events SEC(".maps");

 SEC("uretprobe/bash_readline")
+
 int uretprobe_bash_readline(struct pt_regs *ctx) {
        struct event_t event;

        event.pid = bpf_get_current_pid_tgid();
        bpf_probe_read(&event.str, sizeof(event.str), (void *)PT_REGS_RC(ctx));

+       bpf_probe_read(&event.arg1, sizeof(event.arg1), (void*)ctx->rsi);
+
        bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &event, sizeof(event));

        return 0;
```

A reason why I checked ```ctx->rsi``` is because gdb shows one of two parameters in the function ```foo``` is stored in ```rdi``` and ```rsi``` registers.
```
(gdb) disas foo
Dump of assembler code for function foo:
   0x000000000000115a <+0>:     push   %rbp
   0x000000000000115b <+1>:     mov    %rsp,%rbp
   0x000000000000115e <+4>:     mov    %rdi,-0x8(%rbp)
   0x0000000000001162 <+8>:     mov    %rsi,-0x10(%rbp)
   0x0000000000001166 <+12>:    mov    -0x8(%rbp),%rax
   0x000000000000116a <+16>:    mov    %eax,%edx
   0x000000000000116c <+18>:    mov    -0x10(%rbp),%rax
   0x0000000000001170 <+22>:    add    %edx,%eax
   0x0000000000001172 <+24>:    pop    %rbp
   0x0000000000001173 <+25>:    retq
End of assembler dump.
```

Thank you

**Comment by hyunsooda** [comment]
I could see the parameter values (a purpose of the above example) using libbpf [libbpf](https://github.com/libbpf/libbpf). I don't know how ```cilium/ebpf``` restrict reading some data. Would you please let me know if you know the behavior or policy difference between them?

Thank you

**Comment by ti-mo** [comment]
> The function foo was exported but it occurs an error.

Which error? Impossible to see what's going on without error output.

> I don't know how `cilium/ebpf` restrict reading some data.

It does not.

**Comment by hyunsooda** [comment]
>Which error? Impossible to see what's going on without error output.

It's a runtime error when traps bpf program into target binary, compiled using clang, not gcc.

The runtime error:
```
2021/08/02 19:08:20 creating uretprobe: creating perf_uprobe PMU: symbol 'foo' not found: file does not exist
```

Checking whether it is exported correctly:
```
$ objdump -x simpleapp
00000000004008b0 g     F .text  000000000000001e              foo
```

My two questions in this thread are:
1. Reasoning why runtime error occurs even the target function is explicitly exported.
2. Reading members in ```pt_regs``` seems not working.

My two questions are currently solved (1) by compiling ```clang``` and using the library ``libbpf```. You can close this thread if you consider this trivial.

**Comment by mmat11** [comment]
@ti-mo I guess the error is this one: https://github.com/cilium/ebpf/blob/master/link/kprobe.go#L231. IIRC uprobes can be set even if the offset is bad so probably the filepath is wrong. As I see from the diff, the uprobe API has been called with a relative filepath and that may be a problem, but still, there shouldn't be a difference between compiling the binary with gcc or clang.

@hyunsooda could you try using the absolute filepath? Also could you try using the `PT_REGS_PARM*` macros for accessing pt_regs?

**Comment by hyunsooda** [comment]
Hi @mmat11 

I changed to the absolute path but still not working with the same error. Is there set of macro family ```PT_REGS_PARM*```? I couldn't find them and only can see ```PT_REGS_RC``` in ```ebpf/examples/headers```.

**Comment by mmat11** [comment]
@hyunsooda for "same error", you mean this one?

> 2021/08/02 19:08:20 creating uretprobe: creating perf_uprobe PMU: symbol 'foo' not found: file does not exist

If yes, could you make a repo/gist with a minimal reproducible example?

As for the `PT_REGS_PARM*` macros, they are part of [bpf_tracing.h](https://elixir.bootlin.com/linux/latest/source/tools/lib/bpf/bpf_tracing.h). The header file in the examples folder is a custom header which contains only definitions used in the examples.
Could you try doing: `event.arg1 = PT_REGS_PARM1(ctx)` (I'm just guessing)? Also doublecheck the types in all 3 places (you are using `long long int` in your probed C program, `int` in the ebpf part and `uint32` in your userspace part)

**Comment by hyunsooda** [comment]
Oh, I made a big mistake. 

Two parameters of probed function type are not pointers, but my code regarded two parameters as pointers with ```bpf_probe_read```. Therefore, it leads to an unexpected read since two registers have scalar values, not pointers.

I checked again with pointer types, and it works. Also, I checked it's working with scalar type with direct access, not ```bpf_probe_read```. Sorry for my noise.

**Comment by ti-mo** [comment]
@hyunsooda Have you been able to solve the `symbol 'foo' not found: file does not exist` error? The `file does not exist` should arise from the file not being found on the file system. Perhaps this error could be improved.

**Comment by hyunsooda** [comment]
@ti-mo, Yes, that's the still remaining error when using compiled binary via ```clang``` (I used clang-10)

**Comment by lmb** [comment]
@hyunsooda can you give `master` another try? It should have some code that fixes this.
