### ISSUE TITLE
about bpf map RingBuf

### ISSUE THREAD

**Issue by glennWang** [cilium/ebpf#379]
As the introduction said of v0.6.2 release, cilium/ebpf has support RingBuf.

The problems is that: 
how to use ring_buffer__poll() on userspace and get data ?

**Comment by glennWang** [comment]
I find this pr, and it work ok. 

If there is a branch fot it, go mod can be used, and it is more convenient than vendor copy.

https://github.com/cilium/ebpf/tree/3d2f660cf920a9008430eacad7d6b3af137f1052

**Comment by ti-mo** [comment]
https://github.com/cilium/ebpf/pull/318 is currently undergoing review, and will be merged when it's ready.
