### ISSUE TITLE
Revisit `TestProgAttachCgroupAllowMulti` test

### ISSUE THREAD

**Issue by aditighag** [cilium/ebpf#398]
While working on a PR related to the cgroup package, I noticed that the test [TestProgAttachCgroupAllowMulti](https://github.com/cilium/ebpf/blob/master/link/cgroup_test.go#L47) isn't working as expected. The test passes even when `flagAllowMulti` is removed when attaching the initial cgroup program. I added debug statements, and noticed that only the first program is getting attached to the test cgroup hierarchy (I purposely changed the `attachType` of the 1st program). 
Also, I noticed that the test calls `testLink` helper which in turns calls [link.Update](https://github.com/cilium/ebpf/blob/6e9c8189c02583a221e8792134d5c6818057e802/link/link_test.go#L167). In this particular test case, we don't want to replace the original program with a new one, we want both to the attached at the same time with the multi flag. I suppose we are simply reusing the `Update` function as `Replace` field is unset?

```
$ sudo bpftool cgroup show /sys/fs/cgroup/unified/ebpf-link075329396
ID       AttachType      AttachFlags     Name
200425   ingress
```

/cc @lmb

**Comment by lmb** [comment]
I had to refresh my mind, but I think the test is working correctly. Keep in mind that progAttachCgroup is used as a fallback for a bpf_link based cgroup attachment, hence it's meant to follow the same semantics:

- Multiple cgroup bpf_link can be active on one cgroup
- Each cgroup bpf_link can be updated to change the active program

The test is not intended to check that we can attach multiple programs, it's there to make sure we can update an existing program in the presence of `flagAttachMulti`: https://github.com/cilium/ebpf/blob/65c96b6c3b0487c521c8c2b67f734e42881c017a/link/cgroup.go#L128-L134

**Comment by aditighag** [comment]
>  Keep in mind that progAttachCgroup is used as a fallback for a bpf_link based cgroup attachment, 

Can you elaborate on this? Fallback to...?

> hence it's meant to follow the same semantics:
> * Multiple cgroup bpf_link can be active on one cgroup
> * Each cgroup bpf_link can be updated to change the active program
> 

So the current test is only validating the 2nd case? 

> The test is not intended to check that we can attach multiple programs, it's there to make sure we can update an existing program in the presence of `flagAttachMulti`:
> 
> https://github.com/cilium/ebpf/blob/65c96b6c3b0487c521c8c2b67f734e42881c017a/link/cgroup.go#L128-L134

Gotcha! I was missing this context.

**Comment by lmb** [comment]
> Can you elaborate on this? Fallback to...?

It's used when running on an old kernel that doesn't have bpf_link for cgroups.

> So the current test is only validating the 2nd case?

Correct!

**Comment by aditighag** [comment]
Thanks for the context! I'll close this one out. I may extend the test file to validate the main case where multiple programs can be attached to a cgroup.
