### ISSUE TITLE
Error attaching uprobe to a symbol in a simple Go binary likely due to relocation

### ISSUE THREAD

**Issue by prashantv** [cilium/ebpf#399]
I tried to attach a uprobe to a simple Go binary, but it keeps failing with `creating perf_uprobe PMU: symbol 'main.helloWorld' not found: file does not exist`

After digging into this a little, it seems related to the offset passed in (based on the address for a symbol). The offset should be the symbol's offset in the file, rather than the relocated offset in memory, but the elf parser returns relocated addresses.

I created a simple repro (which includes a precompiled bpf object file, which will likely require BTF-enabled kernel to run)

https://github.com/prashantv/cilium-ebpf-relocate-bug

This repo contains:
 * a simple Go binary that calls `main.helloWorld` every second. Run this using `./helloworld.sh`
 * a very simple uprobe BPF program which just prints the SP when the probe is triggered
 * a Go binary using cilium/ebpf to attach the above bpf program as a uprobe to a `main.helloWorld` symbol, can be run using `./gotrace.sh`

I've been able to successfully use bpftrace, `./bpftrace.sh` prints 
```
$ ./bpftrace.sh
+ pgrep helloworld
333182
+ sudo bpftrace -e 'uprobe:helloworld/helloworld:main.helloWorld { printf("%d\n", (int64)(sarg1)); }'
Attaching 1 probe...
50
51
[..]
```

However, when I try to run the go binary to load the uprobe program, it fails,
```
$ ./gotrace.sh
2021/09/01 13:59:25 failed to load uprobe: failed to attach uprobe: creating perf_uprobe PMU: symbol 'main.helloWorld' not found: file does not exist
```

We can manually find the offset of the symbol, and then subtract the base address of the relocation,
```
> nm helloworld/helloworld | grep main.helloWorld
0000000000497900 T main.helloWorld
> cat /proc/$(pgrep helloworld)/maps
00400000-00498000 r-xp 00000000 fd:00 11638944                           /home/prashant/go/src/github.com/prashantv/cilium-ebpf-relocate-bug/helloworld/helloworld
00498000-00537000 r--p 00098000 fd:00 11638944                           /home/prashant/go/src/github.com/prashantv/cilium-ebpf-relocate-bug/helloworld/helloworld
00537000-0054d000 rw-p 00137000 fd:00 11638944                           /home/prashant/go/src/github.com/prashantv/cilium-ebpf-relocate-bug/helloworld/helloworld
[...]

# we need to subtract 00400000 from 0000000000497900
# which == 0000000000097900  
```

Using this offset with the cilium/ebpf works fine:
```
> ./gotrace.sh -offset 0x0000000000097900
2021/09/01 14:01:19 Success!

# and we see output in the trace_pipe
> sudo cat /sys/kernel/tracing/trace_pipe
       <...>-333215  [000] d... 37055.324585: bpf_trace_printk: UPROBE ENTRY probe triggered, ctx->sp: 66f60

       <...>-333215  [000] d... 37056.325094: bpf_trace_printk: UPROBE ENTRY probe triggered, ctx->sp: 66f60
[...]
```

We can see similar logic in uprobe:
https://github.com/brendangregg/perf-tools/blob/master/user/uprobe#L182

https://www.kernel.org/doc/Documentation/trace/uprobetracer.txt does have some information about this too.
(Related Slack conversation: https://cilium.slack.com/archives/CKC55JL8L/p1629498661062000)

**Comment by lmb** [comment]
Thanks for the detailed bug report! @mmat11 can you take a look when you have a minute?

**Comment by ti-mo** [comment]
Isn't this what https://github.com/cilium/ebpf/pull/385 is supposed to address?

**Comment by mmat11** [comment]
> Isn't this what #385 is supposed to address?

Correct. In the last few days I've been trying to debug what is happening with Go binary + debugfs + kernel 4.9 without success. With kernel version 4.14 and up it works

**Comment by lmb** [comment]
@prashantv can you give `master` a try?

**Comment by prashantv** [comment]
Verified that #385 fixes this issue (updated to master on my repro, and it works with just the symbol)

Thanks for the prompt resolution @mmat11 and @lmb!
