### ISSUE TITLE
How to use BPF_MAP_TYPE_PERCPU_ARRAY in cilium ebpf?

### ISSUE THREAD

**Issue by hao-lee** [cilium/ebpf#400]
Hello,

I changed the map type from `BPF_MAP_TYPE_ARRAY` to `BPF_MAP_TYPE_PERCPU_ARRAY` in `examples/kprobe/bpf/kprobe_example.c` and it gave me an error message when running:

```
reading map: per-cpu value requires pointer to slice
```

I can'f find any material about the correct usage.

**Comment by florianl** [comment]
Hey :wave: 
Just replacing the type of the eBPF map in `examples/kprobe/bpf/kprobe_example.c` is not enough. The error comes from the user space side. When you read from a `BPF_MAP_TYPE_PERCPU_ARRAY` a slice to is expected as you will get the value from every CPU for the given lookup key.

**Comment by hao-lee** [comment]
Thanks, bro. This saves my life! I have finally figured out the usage now.

**Comment by ti-mo** [comment]
@hao-lee Feel free to contribute (or extend) an example, this could be useful to other users as well!

**Comment by hao-lee** [comment]
@ti-mo No problem 😏 I can't wait to do that.
