### ISSUE TITLE
How to deal with multiple C files when using go:generate

### ISSUE THREAD

**Issue by hao-lee** [cilium/ebpf#404]
Hello.

I want to put some C code in a separate file - say `common.c`. How should I modify the `go:generate` line to compile all C files correctly. The following line doesn't seem to work. Thanks!

```
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang-11 Handler ./bpf/kprobe.c ./bpf/common.c -- -I ../headers
```

**Comment by lmb** [comment]
You're right that bpf2go doesn't support multiple .c at the moment. The most common approach to this is to have a file `common.h` which then has functions like so:

```C
static inline __attribute__((__always_inline__)) common_func(int) { ... }
```

You can then include `common.h` from `kprobe.c`. In the future you can use our Slack for questions like this, you'll get quicker answers there.

**Comment by hao-lee** [comment]
Thanks.

**Comment by kmahyyg** [comment]
Almost another year passed, problem still exists...
