### ISSUE TITLE
btf.Spec.FindType copies type

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#416]
In 65df3d1d33f1196ce65d44d6171248274d38ed17 I tried to change the semantics of btf.Spec.FindType so that it doesn't return a copy of a type, but the type itself. Invocation of FindType looks like this:

```
var iphdr Struct
err = spec.FindType("iphdr", &iphdr)
```

Note that we "allocate" a full `iphdr Struct` and pass a pointer to that. `FindType` then copies the result into the pre-allocated `iphdr`, performing a shallow copy. To express the semantics I'd like a call would have to look something like this:

```
var iphdr *Struct
err = spec.FindType("iphdr", &iphdr)
```

It's not possible to express the type we'd like to accept in `FindType` except via `interface{}` and reflection.

**Comment by lmb** [comment]
cc @brb

**Comment by pippolo84** [comment]
Hi @lmb, I started writing a fix for this bug a little bit before you assigned yourself this issue.

I think I came up with a solution. If you are still interested, you can see my fix here: https://github.com/pippolo84/ebpf/tree/bugfix/find-type-copies-type

In short, I changed `FindType` to expose the API you suggested, and added some runtime checks to make sure that the underlying type was acceptable, so to avoid panicking.
Finally, I added a test to check that, for multiple calls with the same type name, the returned addresses are the same.

The work needs to be polished, but I would like to finish it, if still needed.

**Comment by lmb** [comment]
Nice, please continue with your work! I got as far as c334d32a56a2d12c1302002578d2cc1d4f1220c8 which doesn't have tests yet. My accepts both `**T` and `*Type`, but I prefer your solution of changing `resolveBTFType` instead.

From a quick glance:
* You need a check that `typ != nil`
* What is the difference between `ConvertibleTo` and `AssignableTo`?

It'd also be nice if you could add some tests for weird `typ` arguments, like `nil`, `Type`, `*Type` (these should error).

**Comment by pippolo84** [comment]
> * You need a check that `typ != nil`

We should be fine checking that `reflect.ValueOf(typ).Kind() == reflect.Ptr`. In fact, I added a test for the `nil` value and `FindType` returned an error as expected.

> * What is the difference between `ConvertibleTo` and `AssignableTo`?

For non constant values, being convertible to a type seems to be less demanding that being assignable: https://golang.org/ref/spec#Conversions.
For our purpose I think there should be no differences, but I'll stick to `AssignableTo` since it is exactly what we will be doing at the end of the method.
