### ISSUE TITLE
LLVM 10 emits incompatible BTF

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#43]
When using LLVM 10 to compile to eBPF, the generated BTF seems invalid:

```
--- FAIL: TestLoadCollectionSpec (0.00s)
    --- FAIL: TestLoadCollectionSpec/loader-clang-10.elf (0.00s)
        elf_reader_test.go:76: invalid argument: magic: 0xeb9f
            version: 1
            flags: 0x0
            hdr_len: 24
            type_off: 0
            type_len: 536
            str_off: 536
            str_len: 582
            btf_total_size: 1142
            [1] STRUCT (anon) size=40 vlen=5
            	type type_id=2 bits_offset=0
            	key type_id=6 bits_offset=64
            	value type_id=6 bits_offset=128
            	max_entries type_id=2 bits_offset=192
            	map_flags type_id=2 bits_offset=256
            [2] PTR (anon) type_id=4
            [3] INT int size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
            [4] ARRAY (anon) type_id=3 index_type_id=5 nr_elems=1
            [5] INT __ARRAY_SIZE_TYPE__ size=4 bits_offset=0 nr_bits=32 encoding=(none)
            [6] PTR (anon) type_id=7
            [7] TYPEDEF uint32_t type_id=8
            [8] INT unsigned int size=4 bits_offset=0 nr_bits=32 encoding=(none)
            [9] VAR btf_map type_id=1 linkage=1
            [10] FUNC_PROTO (anon) return=3 args=(3 arg)
            [11] FUNC helper_func2 type_id=10 vlen != 0
```
(The error message is from the kernel.)

According to the BTF spec, it is indeed invalid for a FUNC to have a vlen != 1. Maybe this is some kind of new extension?

**Comment by lmb** [comment]
Seems like this is due to https://github.com/llvm/llvm-project/commit/fbb64aa69835c8e3e9efe0afc8a73058b5a0fb3c

**Comment by iAklis** [comment]
It seems that I encountered a same problem, my LLVM version is

> clang version 11.0.0 (https://github.com/llvm/llvm-project.git bdcbdb484829c518511eece0809cc8ce1baa73c8)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /usr/local/bin
> Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1
> Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/9.2.1
> Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/9.2.1
> Candidate multilib: .;@m64
> Candidate multilib: 32;@m32
> Selected multilib: .;@m64

A palliative solution I have tried is 
`
llvm-strip ./xxx.bpf.o --no-strip-all -R .BTF
`

**Comment by lmb** [comment]
Yup, the other fix is to run a bleeding edge kernel!
