### ISSUE TITLE
bpf2go: go-test breaks when the BPF programs have not been checked into source control

### ISSUE THREAD

**Issue by blanquicet** [cilium/ebpf#432]
After updating our project to use `cilium/ebpf v0.6.3-0.20210910140648-4d5607ee169`, we noticed that, as per #327, the skeleton generated by `bpf2go` is now pulling in the BPF elfs using the embed package instead of a literal string.

Updating the skeleton in our project is making the unit-tests fail when the BPF programs have not been built before. In general, we would like basic unit-tests to work with `go test ./...` even if the developer is trying on alternative OSes (Windows) and without installing additional dependencies like clang:
```
$ go test -test.v ./... 
Error: pkg/gadgets/socket-collector/tracer/itertcpv4_bpfel.go:113:12: pattern itertcpv4_bpfel.o: no matching files found 
Error: pkg/gadgets/socket-collector/tracer/itertcpv4_bpfel.go:113:12: pattern itertcpv4_bpfel.o: no matching files found 
Error: make: *** [Makefile:78: test] Error 1 
Error: Process completed with exit code 2.   
```

We could bypass this error by using `-tags` flags on the `bpf2go` command and the build constraints to use a fake skeleton where `.o` is not embedded when running anything different than the actual building (https://github.com/kinvolk/inspektor-gadget/pull/297). However, adding tags introduce complexity, so I wonder if you have alternative suggestions to solve this issue.

For example, could `bpf2go` have an additional parameter to generate the fake skeleton like we did, so our fake skeleton would have its API kept up to date with future versions of `bpf2go`?

cc @mauriciovasquezbernal @alban @marga-kinvolk

**Comment by lmb** [comment]
Hi, the model for bpf2go is to commit the generated .o into your source control. This was already the case before the change to use embed, it's just that the .o was encoded as a string in the Go file.

**Comment by blanquicet** [comment]
Thanks for the response!

Yes, I agree with you and I will follow your suggestion. Even so, it would be interesting to know if anybody in the community is adopting an alternative solution.

**Comment by lmb** [comment]
Ok! My suggestion is to check out our slack, maybe someone there has another approach :)
