### ISSUE TITLE
Is there a better way to share data structures between go and c?

### ISSUE THREAD

**Issue by duanjiong** [cilium/ebpf#456]
Otherwise the same data structure has to be written once for each side.

**Comment by duanjiong** [comment]
Or is there any tool that can automatically generate the corresponding data structure? For example is it bpf2go that can generate the corresponding data structure of go.

**Comment by mythi** [comment]
> Or is there any tool that can automatically generate the corresponding data structure?

`bpftool gen skeleton`? btw, see "Getting Help" in the README. It's better to join Slack to get the questions answered.
