### ISSUE TITLE
support for LoadPinnedMap on 4.4 kernels

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#457]
loading a pinned map fails on older kernels, since they have neither BPF_GET_MAP_INFO_BY_FD nor useful data in /proc/pid/fdinfo. the library uses the following metadata: name, type, key size, value size, max entries and flags.

* name is optional and not supported on 4.4. we can leave it empty.
* flags are introduced with 4.5, which coincidentally also has info in /proc/fdinfo (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f99bf205dab0). for 4.4 we can assume they are zero.
* type is used to check whether a map is per-CPU or contains fds. 4.4 has BPF_MAP_TYPE_PROG_ARRAY, which we need for MapType.canStoreProgram(). also used in mapSpec.checkCompatibility. we need type from somewhere.
* max entries are used to make iteration safe. is there a safe upper bound we can assume for iteration (2^32?) it's also used for mapSpec.checkCompatibility, could we skip the check if `MaxEntries == 0`?
* key and value size are essential: without them we can't do lookups, etc.

@nplanel proposed to solve this by writing the metadata to a file in a well known location. i think this is not the way to go, it introduces persistent state which we somehow need to manage. it also means that the library can only load pinned maps that it has itself pinned before.

hence my proposal: find ways of milking the necessary metadata out of the kernel. i've found a crazy / neat way to do this for key and value size, see https://github.com/cilium/ebpf/commit/e710b5d0cafe817bb61eb91b9ea08df5593b156c there are still some question marks here: what is the max size for a map value (keys are BPF_STACK_MAX)? if we go with this solution we should also just set up the mmap once and keep it around for the lifetime of the process.

this leaves map type and max entries. for map type we need to find an oracle from the kernel, luckily there are only four types supported on 4.4. any ideas? finally, can we get away without knowing exact max entries?

**Comment by lmb** [comment]
4.4 is now EOL, I'm inclined to keep / freeze support of 4.4 as it is. We currently can't even recompile the 4.4 kernels since the old point release fails to build on modern GCC.

**Comment by ti-mo** [comment]
Fine by me, closing for now.
