### ISSUE TITLE
Improve Makefile usability with `podman`

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#479]
Currently, in order to rebuild testdata using `podman`, make needs to be invoked as follows:
```
CONTAINER_ENGINE=podman CONTAINER_RUN_ARGS= make
```

This is a bit verbose and hard to remember. Perhaps the Makefile could run `command -v podman` and automatically use it when present on the machine?

Also, running rootless containers requires subuids and subgids to be allocated for the current user (see https://github.com/containers/podman/issues/3421#issuecomment-544455837).

```
~ cat /etc/subuid /etc/subgid
timo:100000:65536
timo:100000:65536
```

Since I didn't set it up before running podman for the first time, an extra `podman system migrate` was required to get containers to start properly.

Ideally, this would be documented as well.

**Comment by syscll** [comment]
I can take a stab at this if you like? Should be fairly straightforward.

My only thoughts are what if a user has `podman` installed, but _still_ wants to use `docker`?
