### ISSUE TITLE
when pinning map, possible to fail pinning or have extra chars on end of filename because of non-null terminated string

### ISSUE THREAD

**Issue by hamburgerbun** [cilium/ebpf#51]
this happened more commonly with maps with longer filenames for some reason, but for example, if i were to pin something like
/sys/fs/bpf/aaaaa/cachedConnectionTbl
there was a low chance that the pin would fail due to "No such file or directory" randomly, or a somewhat higher chance the file would be created but it'd end up something like
/sys/fs/bpf/aaaaa/cachedConnectionTbl[&%&%&% 
like there would be random characters attached to the end. I'm guessing it's because in bpfPinObject we directly pass in the pointer to the first character of the filename to pin the bpf object at without checking if it's null terminated, so there's a chance of stuff being slapped onto the end. 

In my case, passing in a string to <Map>.Pin(fileName) with null terminator purposely added to the end seems to fix the issue.

**Comment by lmb** [comment]
Can you try the fix and let me know if it solves your problem? I've not found a way to reproduce the failure unfortunately.

**Comment by hamburgerbun** [comment]
yeah i think that would do it, i'll give it a shot when i get a chance tomorrow, in the meantime i had dodged the issue just by doing this append and passing the result in to pinning
`
if !strings.HasSuffix(s, "\x00") {
    return s + "\x00"
}
return s
`
