### ISSUE TITLE
Reduce BTF parser's memory footprint

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#542]
In its current form, the BTF parser scans and allocates all types in a BTF blob. This can be cost-prohibitive on machines with smaller memory budgets when parsing vmlinux.

One potential example has been reported here: https://github.com/cilium/pwru/issues/45.

This issue is for discussing how we could make BTF parsing less memory-intensive.

---

One possible approach could be JIT-parsing as much as possible by providing an iterator over all types. The string table should be parsed in full, as we need to perform random lookups for inflating types' names. Strings aren't fixed-width, so we'd need to scan the whole string table from the start for performing random lookups.

Aside from a type iterator, we can also support type lookups by ID, which is required for inflating the type graph starting from any existing type with dependent types. (e.g., a struct)

**Comment by lmb** [comment]
> The string table should be parsed in full, as we need to perform random lookups for inflating types' names.

The look up is usually offset -> name, that seems fine without parsing the table? Do you mean an `index` of `name -> id`?

**Comment by lmb** [comment]
I've just merged a couple of improvements which significantly reduce the used memory:

- 2c93040e14ead1005b18d467e4553050133252c3
- 31c4e1cf522f532fafd3d3ae6cec8ceeed8bc059
- 0cb94e8393544cb4eef1d209dbff1965d9409704

**Comment by lmb** [comment]
Memory usage is now at less than half for reading vmlinux, is this still an issue?
