### ISSUE TITLE
Support custom "kernel BTF" locations

### ISSUE THREAD

**Issue by joamaki** [cilium/ebpf#550]
For projects that ship with BTF for kernels without `CONFIG_DEBUG_INFO_BTF` it would useful
to be able to point the library to a custom location, so that a project does not need to invasively
symlink/copy/mount the BTF file into a known location.

Current alternative is to set `TargetBTF` with `NewCollectionWithOptions`, but this takes an `io.Reader`,
and requires parsing the BTF file for each collection that's loaded, which is rather memory and CPU intensive.

Would be great if this could be solved, either by allowing giving hints about the BTF location, or by having `TargetBTF`
take a parsed `btf.Spec`.

**Comment by lmb** [comment]
My preference would be to make it a `btf.Spec`. We haven't done this so far since users don't have access to `btf`, but that is something we should change anyways.

I know that @ti-mo has ideas about moving some parts of `btf` into a public package.

**Comment by ti-mo** [comment]
We'll most likely end up exporting the BTF parser and making the lib take a `btf.Spec` or similar where applicable.

One point to add: we need to add support for parsing kernel module BTF (e.g. `/sys/kernel/btf/nf_conntrack`), since those refer to types declared in vmlinux.

**Comment by lmb** [comment]
I'm guessing the data in /sys only shows up after doing a modprobe, which begs the question how we could test this in CI. We don't build / ship modules at the moment to keep it simple, but we might have to change that.

**Comment by ti-mo** [comment]
Indeed, they show up after modprobes. We could always ship a few BTF blobs (including vmlinux) from `/sys/kernel/btf` from a modules-enabled system in the repo. The downside is vmlinux is a few megabytes big. but this might not be that much of a dealbreaker.

This would also make benchmarking BTF unmarshaling in a reproducible way a bit more straightforward.

**Comment by lmb** [comment]
We already have vmlinux btf, and use it for benchmarks via readVMLinux​(​b​). Is that what you mean?

**Comment by ti-mo** [comment]
Ah, turns out we do! Then adding one or two kernel module BTFs shouldn't pose an issue at all.
