### ISSUE TITLE
Support spin locks in maps

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#56]
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=d83525ca62cf8ebe3271d14c36fb900c294274a2 added support for spin locks stored in array hash and map values. Now that we have rudimentary BTF support we could look at supporting this.

**Comment by mehrdadrad** [comment]
The kernel space already works for sure but I just sent a pull request to support bpf_spin_lock from user space https://github.com/cilium/ebpf/pull/473

**Comment by mehrdadrad** [comment]
Added with eced84a27004c8300e4b9210c6419eb5ed57d3f9
