### ISSUE TITLE
add Program.Run to allow passing all parameters to BPF_PROG_RUN

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#576]
Some recent kernel version introduced `BPF_PROG_RUN`. It's just an alias for `BPF_PROG_TEST_RUN` but it shows that upstream considers RUN to be a basic primitive on programs. Another thing that has become apparent is that the input required by different types of programs differs wildly.

* For some prog types ctx must be null, for others it's optional
* For some prog types data must be null and ctx is required (SK_LOOKUP)

Instead of `TestWithContext` I would add a method `Program.Run(RunOptions) (RunResult, error)`. Names TBD. `RunOptions` contains all the possible fields like `Data`, `Context`, etc. RunResult contains data output, context output, etc. `Test` and `Benchmark` keep the same API but are wrappers around `Run`.

cc @ti-mo

_Originally posted by @lmb in https://github.com/cilium/ebpf/pull/511#pullrequestreview-823817507_

**Comment by lmb** [comment]
See #537 for some discussion on what the default argument for input should be.

**Comment by lmb** [comment]
RunOptions should also include `Reset`, so that program interruption can be handled by the caller.

**Comment by dxuuu** [comment]
`Run(RunOptions)` sounds reasonable to me. Adding a reset callback also sounds good. Just lmk on #647 and I'll send an update

**Comment by lmb** [comment]
This is now in master!
