### ISSUE TITLE
Relocation is not called for some `BPF_CORE_READ`

### ISSUE THREAD

**Issue by eiffel-fl** [cilium/ebpf#586]
Hi.

**Describe the bug**
With changes added in 9d739bdd0fe0fd0651ceb3e7bdcb0c9e9e4e92e1, the relocations sometimes does not occur.

**To Reproduce**
I created a reproducer which loads two eBPF code, one which works smoothly the other which shows the problem.
The only difference between the two is that in the one which works, 3 lines are commented.
You can test it with:

```bash
# In a first terminal:
$ git clone https://github.com/eiffel-fl/cilium-ebpf-problem-reproducer.git
$ cd cilium-ebpf-problem-reproducer
$ docker build -t mntns-erange .
$ docker run --rm --privileged -ti mntns-erange
# In a second terminal:
$ sudo cat /sys/kernel/debug/tracing/trace_pipe
# In a third terminal:
$ nc -lvp 9090                                                           
nc: getnameinfo: Temporary failure in name resolution
# Go back to second terminal.
# problem is the output of the problematic eBPF code, ret -34 is -ERANGE returned BPF_CORE_READ_INTO.
# It occurs because this BPF_CORE_READ_INTO is not rellocated at runtime.
nc-107741  [007] d...  9949.590175: bpf_trace_printk: problem: ret: -34; mntns_id: 0

nc-107741  [007] d...  9949.590191: bpf_trace_printk: ok: ret: 0; mntns_id: -268435456
```

**Expected behavior**
`BPF_CORE_READ_INTO` should not return `-ERANGE` because it should had been relocated.

Best regards and thank you in advance.

**Comment by mauriciovasquezbernal** [comment]
I was able to reproduce it on a different setup, so I don't think it's related to a specific environment. The problem is rather difficult to reproduce actually, if I remove the `kprobe/inet6_bind` program it works fine, the same if the 

```
	socket = *socketp;
	sock = BPF_CORE_READ(socket, sk);
	inet_sock = (struct inet_sock *)sock;
```
or

```
	if (filter_by_mnt_ns && !bpf_map_lookup_elem(&mount_ns_set, &mntns_id))
		goto cleanup;

	ret = PT_REGS_RC(ctx);
	if (ignore_errors && ret != 0)
		goto cleanup;
``` 

blocks are removed. 

By using llvm-objdump and bpftool we can see that CO:RE relocations related to `BPF_CORE_READ_INTO(&mntns_id, task, nsproxy, mnt_ns, ns.inum);` is not being performed:

```
$ llvm-objdump-12 -S ok_bpfel.o
[...]
       8:	85 00 00 00 23 00 00 00	call 35
       9:	b7 01 00 00 88 0b 00 00	r1 = 295

$ llvm-objdump-12 -S problem_bpfel.o
[...]
      10:	85 00 00 00 23 00 00 00	call 35
      11:	b7 01 00 00 88 0b 00 00	r1 = 2952
```

```
$ sudo bpftool prog dump xlated name ipv4_bind_exit
84: kprobe  name ipv4_bind_exit  tag 34e27bc54470eb0b  gpl
[...]
; task = (struct task_struct*) bpf_get_current_task();
  15: (85) call bpf_get_current_task#-67904
  16: (b7) r1 = 2952
  17: (0f) r0 += r1
  18: (bf) r8 = r10
  19: (07) r8 += -24
; ret = BPF_CORE_READ_INTO(&mntns_id, task, nsproxy, mnt_ns, ns.inum)
  20: (bf) r1 = r8
  21: (b7) r2 = 8
  22: (bf) r3 = r0
  23: (85) call bpf_probe_read_kernel#-66448
[...]

88: kprobe  name ipv4_bind_exit  tag 0ae72ad1af31125b  gpl
[...]
; task = (struct task_struct*) bpf_get_current_task();
  10: (85) call bpf_get_current_task#-67904
  11: (b7) r1 = 2880
  12: (0f) r0 += r1
  13: (bf) r6 = r10
  14: (07) r6 += -24
; ret = BPF_CORE_READ_INTO(&mntns_id, task, nsproxy, mnt_ns, ns.inum);
; ret = BPF_CORE_READ_INTO(&mntns_id, task, nsproxy, mnt_ns, ns.inum);
  15: (bf) r1 = r6
  16: (b7) r2 = 8
  17: (bf) r3 = r0
  18: (85) call bpf_probe_read_kernel#-66448
```

Notice that the original offset 2952 is updated to 2880 only in one of the programs.

**Comment by eiffel-fl** [comment]
I continued to investigate and I think the fact to add or remove code acts in fact on the function inlining or not.
Indeed, if `probe_exit` is marked `__always_inline`, the relocation works.

When it is too big to be automatically inlined by the compiler, then `cilium/ebpf` uses it as function to compute instructions offsets:

```patch
diff --git a/internal/btf/btf.go b/internal/btf/btf.go
index 2eef409..d649b3b 100644
--- a/internal/btf/btf.go
+++ b/internal/btf/btf.go
@@ -286,6 +286,8 @@ func (spec *Spec) splitExtInfos(info *extInfo) error {
                                // subtracting the function's start offset.
                                r.insnOff -= fnOffset
 
+                               fmt.Printf("%s: before: %d; after: %d\n", fn.Name, r.insnOff + fnOffset, r.insnOff)
+
                                ocr[fn.Name] = append(ocr[fn.Name], r)
                        }
                }

```

I added this print to get this:

```
# Good output:
ipv4_bind_entry: before: 0; after: 0
ipv4_bind_exit: before: 88; after: 88
ipv4_bind_exit: before: 152; after: 152
ipv4_bind_exit: before: 200; after: 200
ipv4_bind_exit: before: 480; after: 480
ipv4_bind_exit: before: 544; after: 544
ipv6_bind_entry: before: 0; after: 0
ipv6_bind_exit: before: 88; after: 88
ipv6_bind_exit: before: 152; after: 152
ipv6_bind_exit: before: 200; after: 200
ipv6_bind_exit: before: 480; after: 480
ipv6_bind_exit: before: 544; after: 544
#Bad one, it contains a lot of probe_exit:
ipv4_bind_entry: before: 0; after: 0
ipv6_bind_entry: before: 0; after: 0
probe_exit: before: 88; after: 88
probe_exit: before: 152; after: 152
probe_exit: before: 200; after: 200
probe_exit: before: 480; after: 480
probe_exit: before: 544; after: 544
```

**Comment by eiffel-fl** [comment]
I found the culprit code:
https://github.com/cilium/ebpf/blob/d4100a1f430f7792dd6ab3113a2dbbe6a1c10e82/elf_reader.go#L332

By removing the `.text` section from the `Programs`, these sections will not appear in `*Programs`.
So, when user calls `LoadAndAssign()`, CO-RE relocation will not be done for them which can lead to odd behavior like the one reported here.

**Comment by ti-mo** [comment]
Small update: I have a patch ready that takes care of gathering CO-RE relocations from bpf2bpf subprogs, but still figuring out how we can add a simple test for this.

As it turns out, the tests in `internal/btf/testdata/relocs.c` pass (they return 0) when CO-RE relo execution is simply skipped or forgotten. I'm working on a test program that fails when left unmodified and only passes after CO-RE.

@eiffel-fl Do you have a pressing need to upgrade? If I don't have a test by tomorrow, we can merge as-is and target a bugfix release next week.

Thanks again for the help.

**Comment by eiffel-fl** [comment]
I do not have a pressing need to upgrade.
I tested upstream `cilium/ebpf` because I wanted to test the commit which added `BPF_CORE_READ_BITFIELD` and I discovered this bug by rebasing.
So, take your time to polish your patch and if you want review, feel free to ping.
