### ISSUE TITLE
examples: adapt kprobe example to the new library version

### ISSUE THREAD

**Issue by amir9339** [cilium/ebpf#635]
**Describe the bug**
The `kprobe` and `ringbuffer` examples are not adapted to the new library version.
Super easy to fix as you already did at https://github.com/cilium/ebpf/pull/389

**To Reproduce**

```sh
go run -exec sudo ./kprobe
go run -exec sudo ./ringbuffer
```

**Expected behavior**
The commands returned this message:

```
# ./ebpf/examples/kprobe
kprobe/main.go:44:24: not enough arguments in call to link.Kprobe
        have (string, *ebpf.Program)
        want (string, *ebpf.Program, *link.KprobeOptions)
```

**Comment by lmb** [comment]
Thanks, this should be fixed in master.
