### ISSUE TITLE
Add some XDP examples

### ISSUE THREAD

**Issue by diegobes** [cilium/ebpf#645]
There are several examples of different ebpf program types but none for XDP.
Can you please add an example of how to use link/program to attach, deatach, pin, unpin xdp programs and maps ?

Thanks

**Comment by Cyc1ing1313** [comment]
agree

**Comment by ti-mo** [comment]
We'll add an example for attaching XDP progs using the `link` package. We could add a fallback using netlink later on if the kernel doesn't support bpf_link, but let's start with a simple example.

@diegobes Pinning is already demonstrated in other examples, is there something specific that needs to be highlighted?

**Comment by lmb** [comment]
We have an XDP link example thanks to @wedaly now.
