### ISSUE TITLE
LoadAndAssign() should explicitly close all resources it doesn't assign

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#701]
I got nerdsniped on Slack and replaced the `sys.FD` finalizer with:
```go
func (fd *FD) finalize() {
	if fd.raw != -1 {
		panic(fmt.Sprintf("forgot to close fd %d", fd.raw))
	}
}
```

This broke a few tests, some where Close() was omitted, mostly around the use of `LoadAndAssign`.

`collectionLoader.finalize()` should only remove the maps and progs that were successfully assigned at least once. It shouldn't zero out `cl.maps` and `cl.programs`, because that relies on finalizers running, which might just never happen.

**Comment by lmb** [comment]
Interesting! Maybe we could add some code that surfaces these bugs when running tests?

Something like:
- allow changing the behaviour to panic at runtime. This could be `var internal.FinalizerShouldPanic bool`
- set the flag from tests and invoke runtime.GC at the end of TestMain.

**Comment by ti-mo** [comment]
I've been experimenting with a few approaches, but it does feel like we need some sort of global to toggle this behaviour. I was also thinking I'd probably want to run actual applications with this enabled in the future, since there will be a lot of upcoming refactoring work in Cilium where this would be incredibly handy. (it currently stuffs maps (created by an old internal bpf/ package, not the lib) containing live fds into package-global vars, and their lifecycle is kind of undefined)

I have a branch with all 'internal' leaks ironed out: https://github.com/ti-mo/ebpf/tree/tb/leaking-fds (grab some eye bleach)

For tests, panicking is okay, but also very annoying to debug, since the panic occurs within the runtime and there's no stack info available. In my hack branch, I've added two string fields, one `metadata` for annotating the fd with a name from within `newProgramWithOptions` etc., and another string to stuff the value of `runtime.Stack()` into from `NewFD()` so when the FD is finalized, there's info available about where it was created.

For anything other than tests, `panic()` is not acceptable, so I was thinking of some kind of notification mechanism that callers can subscribe to in order to receive updates when a GC closes an FD.

There are a few shortcomings to this approach:

- Stack/metadata collection would only start when there is at least one subscriber, but that might result in messages without any metadata if fds were created before the first subscriber. Probably unavoidable and acceptable.
- `runtime.Stack()` needs preallocated buffers, so we need a `sync.Pool` and some mechanism that keeps track of the minimum buffer size required to fit a stack trace. This overhead will grow the deeper the call stack becomes. Haven't found any way to make this more efficient.
