### ISSUE TITLE
bpf-to-bpf calls to static functions at offset != 0 are broken

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#72]
The following doesn't load:

```C
int foo();
static int bar();

__section("socket") int prog() {
        return foo() + bar();
}
```

This is because the call to bar is encoded differently than the call to foo(). Andrii Nakryiko explains the [issue very well](https://lkml.org/lkml/2020/1/24/148).

**Comment by bitness** [comment]
Sorry for posting in an old, closed issue, but is it possible this is broken again? I'm unable to get a program that does the following to load through cilium/ebpf v0.10.0, though it works fine with libbpf:

```
static inline struct nfs_inode* NFS_I(const struct inode* inode)
{
    return container_of(inode, struct nfs_inode, vfs_inode);
}

SEC("fexit/nfs_rmdir")
int BPF_PROG(nfs_rmdir, struct inode* dir, struct dentry* dentry, int ret)
{
    struct nfs_inode* nfsi = NFS_I(dir);
    ....
}
```
The error I get when trying to load this with cilium/ebpf is:
```
verifier error: load program: invalid argument:
        func#0 @0
        R1 type=ctx expected=fp
        0: R1=ctx(id=0,off=0,imm=0) R10=fp0
        ; int BPF_PROG(nfs_rmdir, struct inode* dir, struct dentry* dentry, int ret)
        0: (85) call unknown#195896080
        invalid func unknown#195896080
        processed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
```

Thanks!

**Comment by ti-mo** [comment]
What's `container_of`? `NFS_I` gets inlined, so that's not going to emit a bpf2bpf call. Please open an issue with a reproducer. 🙏

**Comment by bitness** [comment]
`container_of` is a macro from the kernel that lets you get the pointer to a struct that contains a pointer that you have:
```
#ifndef offsetof
#define offsetof(TYPE, MEMBER)  ((unsigned long)&((TYPE *)0)->MEMBER)
#endif
#ifndef container_of
#define container_of(ptr, type, member)                         \
        ({                                                      \
                void *__mptr = (void *)(ptr);                   \
                ((type *)(__mptr - offsetof(type, member)));    \
        })
#endif
```
In the code I posted above, it's saying, "I have a `struct inode*` that I know is the `vfs_inode` field in a `struct nfs_inode`. Please give me a pointer to that `struct nfs_inode`".

I'll open an issue. Thanks for the fast response!
