### ISSUE TITLE
Reference kernel symbols using `__ksym`

### ISSUE THREAD

**Issue by flyth** [cilium/ebpf#761]
**Describe the bug**
Similarly to #698, it's currently not possible to use __ksym, as it's not yet supported by `cilium/ebpf`
https://github.com/cilium/ebpf/blob/9014db4ffb206443cde9f2af7340706f02c6aa5a/btf/btf.go#L407-L408

**To Reproduce**
Try bpf2go on a file including (and using) something like
```
extern const void bpf_link_fops __ksym;
```

In my case, I've used `pid_iter.bpf.c` from `libbpf/bpftool`:
https://github.com/libbpf/bpftool/blob/ee48503a53f6f09a3261e15c3843a3becb9645e0/src/skeleton/pid_iter.bpf.c#L18-L21

This will result in:
```
can't load BPF from ELF: load BTF: reference to .ksyms: not supported
```

**Expected behavior**
We should be able to use __ksym just like in the example from `libbpf/bpftool`.

**Comment by lmb** [comment]
We have kfunc / `__ksym` support now.
