### ISSUE TITLE
cilium/ebpf cannot support btf elf file without .symbol section

### ISSUE THREAD

**Issue by zhangzju** [cilium/ebpf#763]
**Describe the bug**

I want to use BTF file with ELF format to apply my program in lower version kernel, but got an error like
found but load with can't read symbols: no symbol section
this error occurred because the btf package loadSpecFromELF to extract the btf information from .BTF section, but validate it with variableOffsets function witch will throw an error if .symbo section not exist, unfortunately, i stripped most section for easier distribution, when I change the variableOffsets function to this, it works well.

func variableOffsets(file *internal.SafeELFFile) (map[variable]uint32, error) {
	symbols, err := file.Symbols()
	if err != nil {
		return nil, fmt.Errorf("can't read symbols: %v", err) // this is the original code 
		// return nil, nil //this is my modification, works well when I apply the change in vendor
	}

**To Reproduce**
this is my elf file format in readelf -S
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .BTF              PROGBITS         0000000000000000  00000158
       000000000036a01f  0000000000000000   A       0     0     1
  [ 2] .shstrtab         STRTAB           0000000000000000  0036a177
       0000000000000010  0000000000000000           0     0     1

```sh
readelf -S /etc/btf/vmlinux-4.19.91-25.6.al7.x86_64
```

**Expected behavior**

So is there any better solution? or a new pr to compromise? I have tried libbpf to load the btf file and .symbol section is not required, this is what I want to report.

**Comment by ti-mo** [comment]
Interesting, it's true that symbols are not required for parsing vmlinux BTF. How did you generate those ELFs? It sounds like you're hacking them together somehow, maybe after generating BTF using pahole?

In that case, why bother with rolling ELFs at all instead of just distributing naked BTF blobs? `btf.LoadSpecFromReader` supports both.

**Comment by zhangzju** [comment]
> 

thanks for your reply!
1. I generate those bare .BTF elf files by llvm-objcopy after pahole:
`llvm-objcopy --only-section=.BTF --set-section-flags .BTF=alloc,readonly --strip-all mybtffile`
the reason is that I want to be compatible for a lot kernel versions without public network access, so I try to reduce the size of those elf files.
2. btf.LoadSpecFromReader did work in this case, I wrapped LoadSpecFromReader in my situation:
`	// if load spec with err, try to extract btf section directly
	btfelf, err := getELFFileFromReader(fh)
	if err != nil {
		return nil, fmt.Errorf("read bare elf:%s", err)
	}

	var (
		btfSection *elf.Section
	)

	for _, sec := range btfelf.Sections {
		switch sec.Name {
		case ".BTF":
			btfSection = sec
		default:
		}
	}

	if btfSection == nil {
		return nil, fmt.Errorf("read bare elf: no .BTF section in %s", file)
	}

	if btfSection.ReaderAt == nil {
		return nil, fmt.Errorf("compressed BTF is not supported")
	}

	return btf.LoadSpecFromReader(btfSection.ReaderAt)`

**Comment by ti-mo** [comment]
@zhangzju Great, but I meant you could go one step further, just extract the `.BTF` section's binary contents to a file so you don't need to bother with ELF altogether: https://stackoverflow.com/questions/3925075/how-to-extract-only-the-raw-contents-of-an-elf-section.

e.g. `llvm-objcopy --dump-section .BTF=kernel.btf`

Then just load `kernel.btf` using `btf.LoadSpecFromReader()`.
