### ISSUE TITLE
Maybe a bug translate C struct to Go struct。

### ISSUE THREAD

**Issue by stricklandye** [cilium/ebpf#821]
**Describe the bug**
I write a simple eBPF program which attach(by kprobe and kretprobe) at `vfs_open` and then calculate the latency. Here is original C struct definition (has bug):

```c
struct data_t {
    u32 pid;
    u64 latency;
    char comm[16];
};
```

Go struct definition:

```go
type Data struct {
	Pid     uint32
	Ts      uint64
	Comm    [16]uint8
}
```

Given the struct definition and I print the Go struct info by following code:

```go
	var iter = objs.RetMap.Iterate()
	var key uint64
	var val Data
	// wait a moment to get eBPF map filled
	time.Sleep(time.Second * 2)
	var ok = iter.Next(&key, &val)
	for ok {
		fmt.Println(val.Pid, val.Ts, string(val.Comm[:]))
		objs.RetMap.Delete(&key)
		ok = iter.Next(&key, &val)
	}
```

Finally I get following confusing info:

```shell
PID     Latency          Comm
1200687 1086626725888     ps          
1200689 5123895984128     grep        
1200685 3122441224192     rm          
5030 9637906612224     process reap
```

The latency is far beyond correct value which should be roughly hundred us. I convert latency(1086626725888,first row) to binary format and get `1111 1101 0000 0000 0000 0000 0000 0000 0000 0000`,it seems padding so many useless zeros.

But if I exchange `uint64` and `uint32` , everything is fine,correct definition here:

```go
// go struct
type Data struct {
	Ts      uint64
	Pid     uint32
	Comm    [16]uint8
}

// c struct
struct data_t {
    u64 latency;
    u32 pid;
    char comm[16];
};
```

Even, I padding four byte after `uint32` manually within go struct has bugs but c struct remains same ,it also works fine:

```c
// c struct
struct data_t {
    u32 pid;
    u64 latency;
    char comm[16];
};

// go struct
type Data struct {
	Pid     uint32
       // manually padding
	Padding [4]uint8
	Ts      uint64
	Comm    [16]uint8
}
```

**To Reproduce**
I could upload sample code if needed,here is my env:
```sh
go version go1.18.4 linux/amd64
Linux ygjpc 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 22.04.1 LTS 
```

**Expected behavior**
```shell
1271 3176 redis-server    
629520 3183 code            
1 2859 systemd 
```

**Comment by lmb** [comment]
To clarify, when you use the following Go type things work?

```Go
// go struct
type Data struct {
	Pid     uint32
       // manually padding
	Padding [4]uint8
	Ts      uint64
	Comm    [16]uint8
}
```

**Comment by stricklandye** [comment]
@lmb Yes. But if I remove the 4 bytes padding, the bug will appear again.

**Comment by stricklandye** [comment]
I post  code snippet (with bugs)here, other unimportant code is omitted.
**ebpf source code**:
```c

struct data_t {
    u32 pid;
    u64 latency;
    char comm[16];
};


SEC("kprobe/vfs_open")
int kprobe_vfs_open(struct pt_regs *ctx) {
    u64 pid;
    u64 ts;
    pid = bpf_get_current_pid_tgid();
    ts = bpf_ktime_get_ns();
    bpf_map_update_elem(&start_map, &pid, &ts, BPF_ANY);
    return 0;
}
SEC("kretprobe/vfs_open")
int kretprobe_vfs_open(struct pt_regs *ctx) {
    u64 *tsp;

    u64 pid = bpf_get_current_pid_tgid();
    tsp = bpf_map_lookup_elem(&start_map,&pid);
    if (tsp == 0) {
        return 0;
    }
    struct data_t data = {};
    data.pid = pid >> 32;
    data.latency = bpf_ktime_get_ns() - *tsp;
    bpf_get_current_comm(&data.comm,16);
    bpf_map_update_elem(&ret_map,&pid,&data,BPF_ANY);
    bpf_map_delete_elem(&start_map,&pid);
    return 0;
}
```
**main program**:
```go
type Data struct {
	Pid  uint32
	Ts   uint64
	Comm [16]uint8
}

// bpf praogm loading, kprobe ,kreprobe omitted
...

// retrive data from ebpf map
var iter = objs.RetMap.Iterate()
var key uint64
var val Data
// wait a moment to let map to be filled
time.Sleep(time.Second * 2)
for iter.Next(&key, &val) {
     fmt.Println(val.Pid, val.Ts, string(val.Comm[:]))
}

```
**output**:
```shell
1161 43864500994048     redis-server
1046 8486855376896     thermald    
4066 41386304864256     ThreadPoolFo
4116 27595164876800     ThreadPoolFo
219047 22359599742976     popo        
87058 1958505086976     Chrome_IOThr
1035 10475425234944     irqbalance  
```
exchange the  `uint64 TS ` and `uint32 Pid`'s position inside C struct and Go struct,the output is correct,like:
```shell
8394 1161     redis-server
2410 5036     Flushing Dae
3109 4066     ThreadPoolFo
9113 219047     popo        
10032 52597     ACPI Poller 
3905 5036     C2 CompilerT
```

**Comment by mmat11** [comment]
if I understood correctly and you haven't used bpf2go + type flag, I think you either need to manually add padding to the Go struct or use `__attribute__((packed))` on the C struct

**Comment by mmat11** [comment]
`-type` takes the C struct name as argument, see [this example](https://github.com/cilium/ebpf/blob/v0.9.3/examples/tcprtt_sockops/tcprtt_sockops.c#L43-L50) (`-type rtt_event`)

I think the size is different because of Go's optimization: https://go.dev/play/p/kvhUXjE_j-V

**Comment by lmb** [comment]
@mmat11 is right, you either need `-type` or use a packed struct on the C side. If you manually define a Go type that should match the C type you'll have to manually take padding into account. The reason for this is that behind the scene the library uses https://pkg.go.dev/encoding/binary to read the C struct into the Go struct, it's not just a straight memcpy.

**Comment by stricklandye** [comment]
Thanks, I have tried use `-type` flags and it works !
