### ISSUE TITLE
bpf2go: identifiers for UPPER_CASE symbols are not converted

### ISSUE THREAD

**Issue by MarcusWichelmann** [cilium/ebpf#829]
When defining an enum in C like

```c
enum test_enum {
  FOO_BAR,
};
```
and using bpf2go to generate the Go type for that, the resulting Go constant is
```go
const (
  identTestEnumFOO_BAR = 0
)
```
which is pretty far off from how Go identifiers should look like, according to the [spec](https://go.dev/ref/spec#Identifiers).

I'd expect, that such upper case identifiers are converted to PascalCase ones, so that the generated code looks less odd:
```go
const (
  identTestEnumFooBar = 0
)
```

This already works, when the C enum members are written in snake_case (`foo_bar`), just not, when its UPPER_CASE, as it is often seen in C code.

According to [this unit test](https://github.com/cilium/ebpf/blob/master/internal/output_test.go#L14), this behaviour seems to be intended. What was the reason for that?

A more thorough reproduction example can be found in the testdata of this repo: [minimal.c](https://github.com/cilium/ebpf/blob/master/cmd/bpf2go/testdata/minimal.c) [test_bpfel.go](https://github.com/cilium/ebpf/blob/master/cmd/bpf2go/test/test_bpfel.go)

Of course, this behaviour cannot be changed without risking breaking changes, but would you accept a pull request that introduces a flag to configure the identifier conversion like described above?

**Comment by ti-mo** [comment]
`internal.Identifier()` is used to generate `internal/sys/types.go` and is responsible for e.g.
```go
type Cmd uint32

const (
	BPF_MAP_CREATE                  Cmd = 0
	BPF_MAP_LOOKUP_ELEM             Cmd = 1
	...
)
```

This might be stating the obvious, but all-uppercase enum keys like FOO_BAR are widely used in the kernel and C projects in general as globally-unique values that make grepping large codebases possible. Sharing these identifiers between Go and C is desirable, so we're not going to change this behaviour by default. The convention is to stick to CamelCase, but this is still just a convention, not a requirement by spec. We're better off breaking the convention to keep things recognizable here.

It's common to create Go-friendly aliases for frequently-used enums whose names are too long (`const LookupAndDelete = BPF_MAP_LOOKUP_AND_DELETE_ELEM`).

I get the tendency to want to change this, but I'm not convinced it's worth the additional complexity. As I've mentioned, these enums are uppercased for visibility/uniqueness, and it's often better to preserve them to keep things clear and consistent. If this is not required, why not modify the enum on the C side to be lowercased?

**Comment by MarcusWichelmann** [comment]
Ah, thank you for clarifying the reasons why it's currently done like that. Good point with the aliases. We'll probably go this route then.

**Comment by ti-mo** [comment]
Great, thanks for the reply! Closing this.
