### ISSUE TITLE
Figure out map element vs. map batch APIs

### ISSUE THREAD

**Issue by joestringer** [cilium/ebpf#85]
The kernel APIs provide multiple implementations for map interactions:

* Per-element APIs (Since Linux v3.18)
  * Lookup
  * Update
  * Delete
  * GetNextKey (iteration)
  * Lookup + Delete (Linux v4.20, stack/queue maps only)
* Batched APIs (Linux v5.6):
  * Lookup batch
  * Lookup + Delete
  * Update batch
  * Delete batch

Do we want to export both in the library API, or export a batched API and if batch API is unavailable, simulate the batched behaviour using per-element APIs?

Things to keep an eye out for: per-element APIs might not provide the exact same behaviour so we'll have to pay close attention when defining semantics on these map interactions.

**Comment by lmb** [comment]
Personal preference: keep the single vs. batch APIs separate. They have different trade-offs as you mention.

I guess the current spirit of the library is to expose the "raw" functions but then build a nicer abstraction on top of it. Maybe that's possible for batch stuff as well, like a `type MapDumper` or whatever. The use case for batch things is kind of nebulous to me, to be honest.

**Comment by nathanjsweet** [comment]
This is implemented
