### ISSUE TITLE
btf: LoadKernelSpec() is too slow 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [cilium/ebpf#917]
`LoadKernelSpec()` implements a [cache](https://github.com/cilium/ebpf/blob/master/btf/btf.go#L290-L295) mechanism to avoid parsing the BTF each time it's called, even if this helps, further calls to it are still slow because the full spec is [copied](https://github.com/cilium/ebpf/blob/dc0c82204f210e73e853bd0ad96060bb33ec3901/btf/btf.go#L318).

I added some prints to it:

```
LoadKernelSpec took 193.397721ms <-- first call
LoadKernelSpec took 71.852786ms
LoadKernelSpec took 76.223422ms
LoadKernelSpec took 76.203926ms
LoadKernelSpec took 74.56908ms
LoadKernelSpec took 71.979184ms
LoadKernelSpec took 83.94024ms
LoadKernelSpec took 72.563247ms
```

Do we really need to copy the spec each time before returning? If yes, would it make sense to implement a way to avoid such copy for internal callers?

Found by @alban  in https://github.com/inspektor-gadget/inspektor-gadget/pull/1201. 

ref https://github.com/cilium/ebpf/pull/861/commits/3e6faa646b1adaf16134c394413dd7cf223a86db

**Comment by lmb** [comment]
Interesting, that is expensive indeed! We need to copy spec since you can mutate the types contained in it, so distinct callers could interfere with each other. We used to only copy in `TypeByName` methods on the Spec, but that has other problems.

I wonder why it takes so long to copy the spec, can you try profiling it to see where the time goes?

**Comment by alban** [comment]
Using bcc's profile tool, I see the most common stacks are the following:
```
    runtime.mapaccess1
    local.github.com/cilium/ebpf/btf.copier.copy
    github.com/cilium/ebpf/btf.copyTypes
    github.com/cilium/ebpf/btf.(*Spec).Copy
    github.com/cilium/ebpf/btf.kernelSpec
    github.com/cilium/ebpf.applyRelocations
```

```
    runtime.mapassign
    github.com/cilium/ebpf/btf.indexTypes
    github.com/cilium/ebpf/btf.(*Spec).Copy
    github.com/cilium/ebpf/btf.kernelSpec
    github.com/cilium/ebpf.applyRelocations
```
and other GC stacks.

I'll dig deeper and try some optimization.

**Comment by mauriciovasquezbernal** [comment]
I did some profiling using this:

```golang
package main

import (
	"log"
	"os"
	"runtime/pprof"

	"github.com/cilium/ebpf/btf"
)

func main() {
	f, err := os.Create("/tmp/profile.prof")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	pprof.StartCPUProfile(f)
	defer pprof.StopCPUProfile()

	spec, err := btf.LoadKernelSpec()
	if err != nil {
		log.Fatal(err)
	}

	for i := 0; i < 100; i++ {
		spec.Copy()
	}
}
```

[profile.zip](https://github.com/cilium/ebpf/files/10509456/profile.zip)

![pprof002](https://user-images.githubusercontent.com/13031921/214841573-9462c2ed-f198-4ae5-95a0-6768aa1f4087.svg)

It seems much of the time is expended accessing and assigning maps.

**Comment by lmb** [comment]
Can you try https://github.com/cilium/ebpf/pull/826 and see if / how much it helps?

**Comment by mauriciovasquezbernal** [comment]
It seems to be a bit faster, but not fast enough. 

```bash
$ sudo  ./kprobe 
LoadKernelSpec took 185.619052ms
LoadKernelSpec took 71.711941ms
LoadKernelSpec took 73.119972ms
LoadKernelSpec took 75.93887ms
LoadKernelSpec took 74.964084ms
LoadKernelSpec took 60.523513ms
LoadKernelSpec took 82.174331ms
LoadKernelSpec took 59.754125ms
LoadKernelSpec took 74.105258ms
LoadKernelSpec took 70.391765ms
LoadKernelSpec took 78.612154ms
LoadKernelSpec took 70.614646ms
LoadKernelSpec took 73.23505ms
LoadKernelSpec took 60.696961ms
LoadKernelSpec took 60.89296ms
LoadKernelSpec took 69.950004ms
LoadKernelSpec took 73.62297ms
LoadKernelSpec took 73.871118ms
LoadKernelSpec took 75.607055ms
LoadKernelSpec took 57.669741ms
LoadKernelSpec took 58.718424ms
```

**Comment by mauriciovasquezbernal** [comment]
> We need to copy spec since you can mutate the types contained in it, otherwise distinct callers could interfere with each other

Thinking again about it. In which cases a caller would need to mutate the spec returned by `LoadKernelSpec()`?
How about documenting that the caller can't mutate this object and let them make the `Copy()` if needed? If this is definitevely not an option, can't we have a different method that doesn't perform the copy and use it internally?

**Comment by ti-mo** [comment]
We can continue this discussion elsewhere, feel free to open a Slack thread or GH Discussion if you want to explore this further.

To answer your question:

> In which cases a caller would need to mutate the spec returned by LoadKernelSpec()?

Our concern is not that a caller would intentionally intend to modify the vmlinux spec, it's that it's pretty easy to retrieve a type from a spec and inadvertently modify it, e.g. taking a struct/datasec from vmlinux, modifying it without `Copy()`ing it and overriding a MapSpec.Value. The caller may assume it's a copy, but it's actually a pointer into the (now globally-shared) btf.Spec.

If multiple packages depend on ebpf-go, and you write an application that depends on those packages, things will break in bad an unexpected ways. https://github.com/cilium/ebpf/pull/948 is out to partly mitigate this.
