### ISSUE TITLE
rand.Seed() is deprecated in Go 1.20

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#933]
From godoc:
```
// Deprecated: Programs that call Seed and then expect a specific sequence
// of results from the global random source (using functions such as Int)
// can be broken when a dependency changes how much it consumes
// from the global random source. To avoid such breakages, programs
// that need a specific result sequence should use NewRand(NewSource(seed))
// to obtain a random generator that other packages cannot access.
```

Looks like they're pushing against using global entropy pools. Makes sense. We have a few such uses around the codebase:

```
btf/traversal_test.go
15:	rand.Seed(seed)

examples/map_in_map/main.go
50:	rand.Seed(time.Now().UnixNano())
```

The one in tests can be replaced with a helper in `testutils` that creates a new entropy pool. This needs to take care of locking since the default `rand` implementation isn't concurrency safe.

The one in examples can just be replaced with an unlocked source.

**Comment by lmb** [comment]
Great, thanks! Drop into our slack channel if you'd like to discuss.

**Comment by kwakubiney** [comment]
Can I get a link /invite to the Slack channel? @lmb

**Comment by lmb** [comment]
Check out https://github.com/cilium/ebpf/blob/master/CONTRIBUTING.md
