### ISSUE TITLE
Why no tcp/ip info about container

### ISSUE THREAD

**Issue by wanghonglei5181** [cilium/ebpf#964]
**Describe the bug**
when run  go run -exec ./tcprtt_socktops
can not found tcp/ip info about my containers

**To Reproduce**
Steps to reproduce the behavior. Please include:

```sh
go version
go version go1.20.1 linux/amd64

uname -a
 5.14.0-162.6.1

cat /etc/os-release 
NAME="AlmaLinux"
VERSION="9.1 (Lime Lynx)"
```
```
How to reproduce
On machine A
 go run -exec ./tcprtt_socktops
 docker run --cpus 1 -p 80:80 nginx   // works fine
 k8s pod // not output about the container ip
On machine B
 /usr/sbin/wrk -d 10m -c 128 -t 128 http://IP:PORT/ --latency

```

**Expected behavior**
output container tcp/ip info

**Comment by lmb** [comment]
I just tested it on my machine, the example works fine. So it's probably a problem on your side, and therefore not a good candidate for an issue.

Please drop by on slack if you want to debug further.
