### ISSUE TITLE
perf: use the min value of maxentries and possibles cpus to create ring

### ISSUE THREAD

**Issue by chengzhycn** [cilium/ebpf#968]
Ref: https://github.com/cilium/ebpf/pull/965

@lmb Hi, thanks for your reply! I think you mean that we can load bpf object by this lib and it will correct the `maxEntries` value to the possible cpus. But our project is some old. We use `tc` command to load the bpf object, so if we don't hard code a `max_elems` value, the map will be mismatched between the c and go code. And if we set `max_elems` a bigger value than possible cpus, the for loop in `NewReaderWithOptions` will output an error.

**Comment by florianl** [comment]
> We use tc command to load the bpf object [..]

Can you elaborate also more on this? Can you maybe share a minimal example or workflow?
The netlink/tc subsystem of the Linux kernel and the eBPF subsystem are independent of each other. But it is possible to attach a loaded eBPF program to a netlink/tc element. The loading of eBPF programs and maps happens all in the eBPF subsystem.

**Comment by ti-mo** [comment]
@florianl The `tc` and `ip` commands actually contain a bpf loader. :slightly_smiling_face: Before it was ported to work on top of libbpf, it even implemented one completely from scratch, iirc this was the very first ebpf loader. Cilium still uses it, though it's been mostly replaced by the lib. See https://github.com/cilium/cilium/blob/853ec101d8adee8d482040aa038e5b71ce7775e2/bpf/init.sh#L276.

@chengzhycn Could you provide some error output together with the relevant map definition? If you're using tc, you're probably using `bpf_elf_map` with the pinning set to true, then opening the map from a pin using ebpf-go?

**Comment by chengzhycn** [comment]
> If you're using tc, you're probably using bpf_elf_map with the pinning set to true, then opening the map from a pin using ebpf-go?

@ti-mo Exactly. I defined a map in c like this:

```
#define EVENT_MAX_ENTRIES       512

struct bpf_elf_map __section_maps event = {
    .type = BPF_MAP_TYPE_PERF_EVENT_ARRAY,
    .size_key = sizeof(int),
    .size_value = sizeof(__u32),
    .max_elem = EVENT_MAX_ENTRIES,
    .pinning = PIN_GLOBAL_NS,
};
```
using the `tc` command to load this:
```
tc filter add dev eth0 ingress bpf da obj bpf_test.o sec test
```

which the event map pinned at `/sys/fs/bpf/tc/globals/event`. Later, I startup the go program, open this map:
```
	m, err := ebpf.LoadPinnedMap("/sys/fs/bpf/tc/globals/event", nil)
	if err != nil {
		fmt.Printf("err: %v\n", err)
		return
	}

	reader, err := perf.NewReader(m, 8192)
	if err != nil {
		fmt.Printf("err: %v\n", err)
		return
	}
```

then the error output:
```
err: failed to create perf ring for CPU 32: can't create perf event: invalid argument
```

the cpu num of my server is 32.
```
# cat /sys/devices/system/cpu/possible
0-31
```

cc @lmb @florianl

**Comment by lmb** [comment]
Are you able to keep `max_elems` at 0? Newer `libbpf` / `iproute2` should support the same behaviour: https://github.com/libbpf/libbpf/blob/b5e9722ec268702b2ec62863222277148e4fe656/src/libbpf.c#L5184

**Comment by ti-mo** [comment]
@chengzhycn Thanks for sharing some more details, this makes sense. I'm on the fence and kind of have to agree with Lorenz. Letting libbpf auto-size the map would be most straightforward.

Do you have a use case for hot-adding CPUs, or is there a particular reason for setting `EVENT_MAX_ENTRIES 512`? The only benefit of doing this is so you don't have to recreate the map and all dependent programs when you hot-add CPUs to a VM. In that case, the new CPUs already have a ring allocated, and you just need to recreate the perf reader to consume them.

If that's not the case, I'd suggest you omit max_elem, this should just work with modern iproute2.

**Comment by lmb** [comment]
Since there is a work around I'm closing this for now.

**Comment by shach33** [comment]
Hello, 

I am facing the same issue again. My libbpf version is 1:0.5.0-1ubuntu22.04.1. I am not sure what is the workaround here. I am not using max_elem . 

```
struct {
__uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
__uint(size_key, sizeof(__u32));
__uint(size_value, sizeof(__u32));
 
} payload SEC(".maps"); 
```

When I run `NewReaderWithOptions  (payload, os.Getpagesize())`, it errors "failed to create perf ring for CPU 80: can't create perf event: invalid argument" . Can you please suggest what to do. Thanks!
