### ISSUE TITLE
link: support different tracefsPath

### ISSUE THREAD

**Issue by songtao98** [cilium/ebpf#981]
Hi, 

I've noticed that in `link/perf_event.go`, the `tracefsPath` is defined as `"/sys/kernel/debug/tracing"`, why this is fixed? Some information can be refered to this question here about `debugfs` and `tracefs` https://stackoverflow.com/questions/72910257/linux-kernel-tracefs-vs-debugvs

Beyond this scenario, when I use eBPF and tracepoints in container, the volume mount might be changed, and is not `/sys/kernel/debug/tracing`, what can I do in this circumastance? 

So do you consider make this variable configurable or something else?

**Comment by lmb** [comment]
Are you using `master` of the library? We've recently added support for `/sys/kernel/tracing`: https://github.com/cilium/ebpf/blob/5ea5368f9823c13e71146a6c2cca84ad60a5e26a/link/perf_event.go#L446-L462

> when I use eBPF and tracepoints in container, the volume mount might be changed, and is not /sys/kernel/debug/tracing, what can I do in this circumastance?

Do you have an example for this? Unless there is a good reason, the container runtime should make /sys available to you if you configure it correctly.

**Comment by songtao98** [comment]
@lmb Thanks for reply and apologize for not checkingout to main branch. `getTracefsPath` Do support for `/sys/kernel/tracing`. 

> Do you have an example for this? Unless there is a good reason, the container runtime should make /sys available to you if you configure it correctly.

Anyway, still, is there any reason to make the tracefs path fixed? Check this question I asked today for my example. https://stackoverflow.com/questions/75808955/error-mounting-sys-kernel-debug-tracing-to-rootfs
In this situation I cannot see `/sys/kernel/debug/tracing` in my container though I can make it as a volume mount for the whole `/sys`. But another way might be mount it into container as `/host-sys/` directory, and that's when I wanna pass this path into link package. 

However, I've noticed that the recent cilium/ebpf uses **_generics_** based on go 1.18, and our project uses go 1.17 so it statys at cilium/ebpf v0.8.1 and maybe the solution for me has to be overwrite the `/sys` in container by volumemount. :)

**Comment by lmb** [comment]
> Anyway, still, is there any reason to make the tracefs path fixed?

My approach in general is to not make something configurable unless necessary. From your SO question it seems like you don't have a `/sys` in the container at all? If yes I'd argue that the correct fix is to change your container runtime config.

**Comment by songtao98** [comment]
> don't have a /sys in the container at all

I have /sys in my container but ther is no `/sys/kernel/debug/tracing`. 

`-v /sys/fs/debug/tracing:/sys/fs/debug/tracing ` throws an error of 
> Error: failed to create containerd task: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/sys/kernel/debug/tracing" to rootfs at "/sys/kernel/debug/tracing": mkdir /run/containerd/io.containerd.runtime.v2.task/k8s.io/mycontainername/rootfs/sys/kernel/debug/tracing: no such file or directory: unknown

The final solution is use `-v /sys/:/sys/`

**Comment by lmb** [comment]
Did some more searching, seems like this is a common problem that some container runtimes solve, others don't. Since you've found a workaround I'll close the issue.
